# How do I find and remove duplicate rows in pandas?

In [1]:
import pandas as pd

In [10]:
# read a dataset of movies reviewers (modifying the default parameter values for read_table)
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|', header=None, names=user_cols, index_col='user_id')

In [11]:
users.head(15)

         age  gender     occupation  zip_code
user_id
user_id  age  gender     occupation  zip_code
1         24       M     technician     85711
2         53       F          other     94043
3         23       M         writer     32067
4         24       M     technician     43537
5         33       F          other     15213
6         42       M      executive     98101
7         57       M  administrator     91344
8         36       M  administrator     05201
9         29       M        student     01002
10        53       M         lawyer     90703
11        39       F          other     30329
12        28       F          other     06405
13        47       M       educator     29206
14        45       M      scientist     55106

In [12]:
users.shape

(944, 4)

In [13]:
users.zip_code.duplicated()

user_id
user_id    False
1          False
2          False
3          False
4          False
           ...
939        False
940         True
941        False
942        False
943        False
Name: zip_code, Length: 944, dtype: bool

In [14]:
users.zip_code.duplicated().sum()

np.int64(148)

In [15]:
users.duplicated()

user_id
user_id    False
1          False
2          False
3          False
4          False
           ...
939        False
940        False
941        False
942        False
943        False
Length: 944, dtype: bool

In [16]:
users.loc[users.duplicated(), :]

        age gender occupation zip_code
user_id
496      21      F    student    55414
572      51      M   educator    20003
621      17      M    student    60402
684      28      M    student    55414
733      44      F      other    60630
805      27      F      other    20009
890      32      M    student    97301

In [18]:
users.loc[users.duplicated(keep='last'), :]

        age gender occupation zip_code
user_id
67       17      M    student    60402
85       51      M   educator    20003
198      21      F    student    55414
350      32      M    student    97301
428      28      M    student    55414
437      27      F      other    20009
460      44      F      other    60630

In [19]:
users.loc[users.duplicated(keep=False), :]

        age gender occupation zip_code
user_id
67       17      M    student    60402
85       51      M   educator    20003
198      21      F    student    55414
350      32      M    student    97301
428      28      M    student    55414
437      27      F      other    20009
460      44      F      other    60630
496      21      F    student    55414
572      51      M   educator    20003
621      17      M    student    60402
684      28      M    student    55414
733      44      F      other    60630
805      27      F      other    20009
890      32      M    student    97301

In [20]:
users.drop_duplicates().shape

(937, 4)

In [21]:
users.drop_duplicates(keep=False).shape

(930, 4)

In [22]:
users.duplicated(subset=['age', 'zip_code']).sum()

np.int64(16)

In [23]:
users.drop_duplicates(subset=['age', 'zip_code']).shape

(928, 4)