# How do I create a pandas DataFrame from another object?

In [12]:
import pandas as pd

In [22]:
# first create df from dictionary
pd.DataFrame({'id':[100, 101, 102], 'color':['red', 'blue', 'red']})

    id color
0  100   red
1  101  blue
2  102   red

In [23]:
df = pd.DataFrame({'id':[100, 101, 102], 'color':['red', 'blue', 'red']}, columns=['id', 'color'], index=['a','b','c'])
df

    id color
a  100   red
b  101  blue
c  102   red

In [7]:
# create df from list of lists
pd.DataFrame([[100, 'red'],[101, 'blue'], [102, 'red']])

     0     1
0  100   red
1  101  blue
2  102   red

In [8]:
pd.DataFrame([[100, 'red'],[101, 'blue'], [102, 'red']], columns=['id', 'color'])

    id color
0  100   red
1  101  blue
2  102   red

In [14]:
# create df from array of numbers
import numpy as np

arr = np.random.rand(4,2)
arr

array([[0.43954142, 0.58008025],
       [0.77855859, 0.2851412 ],
       [0.97167325, 0.32117078],
       [0.95404001, 0.01280131]])

In [15]:
pd.DataFrame(arr, columns=['one', 'two'])

        one       two
0  0.439541  0.580080
1  0.778559  0.285141
2  0.971673  0.321171
3  0.954040  0.012801

In [16]:
pd.DataFrame({'student': np.arange(100, 110, 1), 'test':np.random.randint(60, 101)})

   student  test
0      100    70
1      101    70
2      102    70
3      103    70
4      104    70
5      105    70
6      106    70
7      107    70
8      108    70
9      109    70

In [17]:
pd.DataFrame({'student': np.arange(100, 110, 1), 'test':np.random.randint(60, 101)}).set_index('student')

         test
student
100        86
101        86
102        86
103        86
104        86
105        86
106        86
107        86
108        86
109        86

In [18]:
s = pd.Series(['round', 'square'], index=['c', 'b'], name='shape')
s

c     round
b    square
Name: shape, dtype: object

In [24]:
df

    id color
a  100   red
b  101  blue
c  102   red

In [26]:
pd.concat([df, s], axis=1)

    id color   shape
a  100   red     NaN
b  101  blue  square
c  102   red   round