# How do I apply a function to a pandas Series or DataFrame?

In [1]:
import pandas as pd

In [4]:
train = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
train.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [5]:
# map function
# if we want to change Sex values to ones and zeros
train['Sex_num'] = train.Sex.map({'female': 0, 'male': 1})

In [7]:
train.loc[0:14, ['Sex', 'Sex_num']]

       Sex  Sex_num
0     male        1
1   female        0
2   female        0
3   female        0
4     male        1
5     male        1
6     male        1
7     male        1
8   female        0
9   female        0
10  female        0
11  female        0
12    male        1
13    male        1
14  female        0

In [9]:
# now, move to apply, which is both: Series method and Dataframe method
# if we want to count length of name 
train['Name_length'] = train.Name.apply(len) # here we use it with Series

In [10]:
train.loc[0:14, ['Name', 'Name_length']]

                                                 Name  Name_length
0                             Braund, Mr. Owen Harris           23
1   Cumings, Mrs. John Bradley (Florence Briggs Th...           51
2                              Heikkinen, Miss. Laina           22
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)           44
4                            Allen, Mr. William Henry           24
5                                    Moran, Mr. James           16
6                             McCarthy, Mr. Timothy J           23
7                      Palsson, Master. Gosta Leonard           30
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)           49
9                 Nasser, Mrs. Nicholas (Adele Achem)           35
10                    Sandstrom, Miss. Marguerite Rut           31
11                           Bonnell, Miss. Elizabeth           24
12                     Saundercock, Mr. William Henry           30
13                        Andersson, Mr. Anders Johan           27
14               Vestrom, Miss. Hulda Amanda Adolfina           36

In [11]:
# another example to round Fare column
import numpy as np
train['Fare_ceil'] = train.Fare.apply(np.ceil)

In [12]:
train.loc[0:14, ['Fare','Fare_ceil']]

       Fare  Fare_ceil
0    7.2500        8.0
1   71.2833       72.0
2    7.9250        8.0
3   53.1000       54.0
4    8.0500        9.0
5    8.4583        9.0
6   51.8625       52.0
7   21.0750       22.0
8   11.1333       12.0
9   30.0708       31.0
10  16.7000       17.0
11  26.5500       27.0
12   8.0500        9.0
13  31.2750       32.0
14   7.8542        8.0

In [15]:
# let's use apply to extract first name from name column
train.Name.str.split(',').head(15) # note that result is list of 2 element, first and first name

0                            [Braund,  Mr. Owen Harris]
1     [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                             [Heikkinen,  Miss. Laina]
3       [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                           [Allen,  Mr. William Henry]
5                                   [Moran,  Mr. James]
6                            [McCarthy,  Mr. Timothy J]
7                     [Palsson,  Master. Gosta Leonard]
8     [Johnson,  Mrs. Oscar W (Elisabeth Vilhelmina ...
9                [Nasser,  Mrs. Nicholas (Adele Achem)]
10                   [Sandstrom,  Miss. Marguerite Rut]
11                          [Bonnell,  Miss. Elizabeth]
12                    [Saundercock,  Mr. William Henry]
13                       [Andersson,  Mr. Anders Johan]
14              [Vestrom,  Miss. Hulda Amanda Adolfina]
Name: Name, dtype: object

In [16]:
# create a function to return first name, and try it with apply method
def get_element(my_list, position):
    return my_list[position]

In [18]:
train.Name.str.split(',').apply(get_element, position = 0) # now we got first name, since posistion = 0

0         Braund
1        Cumings
2      Heikkinen
3       Futrelle
4          Allen
         ...
886     Montvila
887       Graham
888     Johnston
889         Behr
890       Dooley
Name: Name, Length: 891, dtype: object

In [19]:
# also we can done this without using function, instead of it use lambda
train.Name.str.split(',').apply(lambda x : x[0]).head(15)

0          Braund
1         Cumings
2       Heikkinen
3        Futrelle
4           Allen
5           Moran
6        McCarthy
7         Palsson
8         Johnson
9          Nasser
10      Sandstrom
11        Bonnell
12    Saundercock
13      Andersson
14        Vestrom
Name: Name, dtype: object

In [22]:
# now, we also can use apply method with Dataframe
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')
drinks.head(15)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
11,Bahamas,122,176,51,6.3,NaN
12,Bahrain,42,63,7,2.0,AS
13,Bangladesh,0,0,0,0.0,AS
14,Barbados,143,173,36,6.3,NaN

In [23]:
drinks.loc[:, 'beer_servings':'wine_servings']

     beer_servings  spirit_servings  wine_servings
0                0                0              0
1               89              132             54
2               25                0             14
3              245              138            312
4              217               57             45
..             ...              ...            ...
188            333              100              3
189            111                2              1
190              6                0              0
191             32               19              4
192             64               18              4

[193 rows x 3 columns]

In [24]:
drinks.loc[:, 'beer_servings':'wine_servings'].apply(max, axis=1)

0        0
1      132
2       25
3      312
4      217
      ...
188    333
189    111
190      6
191     32
192     64
Length: 193, dtype: int64

In [25]:
drinks.loc[:, 'beer_servings':'wine_servings'].apply(max, axis=0)

beer_servings      376
spirit_servings    438
wine_servings      370
dtype: int64

In [26]:
drinks.loc[:, 'beer_servings':'wine_servings'].apply(np.argmax, axis=1)

0      0
1      1
2      0
3      2
4      0
      ..
188    0
189    0
190    0
191    0
192    0
Length: 193, dtype: int64

In [27]:
# last one is: applymap, applied to every element in df
drinks.loc[:, 'beer_servings':'wine_servings'].applymap(float)

C:\Users\Maryam\AppData\Local\Temp\ipykernel_11924\1341102512.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  drinks.loc[:, 'beer_servings':'wine_servings'].applymap(float)

     beer_servings  spirit_servings  wine_servings
0              0.0              0.0            0.0
1             89.0            132.0           54.0
2             25.0              0.0           14.0
3            245.0            138.0          312.0
4            217.0             57.0           45.0
..             ...              ...            ...
188          333.0            100.0            3.0
189          111.0              2.0            1.0
190            6.0              0.0            0.0
191           32.0             19.0            4.0
192           64.0             18.0            4.0

[193 rows x 3 columns]

In [28]:
# use map instead applymap
drinks.loc[:, 'beer_servings':'wine_servings'].map(float)

     beer_servings  spirit_servings  wine_servings
0              0.0              0.0            0.0
1             89.0            132.0           54.0
2             25.0              0.0           14.0
3            245.0            138.0          312.0
4            217.0             57.0           45.0
..             ...              ...            ...
188          333.0            100.0            3.0
189          111.0              2.0            1.0
190            6.0              0.0            0.0
191           32.0             19.0            4.0
192           64.0             18.0            4.0

[193 rows x 3 columns]

In [29]:
# we can use this to overwrite df
drinks.loc[:, 'beer_servings':'wine_servings'] = drinks.loc[:, 'beer_servings':'wine_servings'].map(float)

In [30]:
drinks.head(15)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
11,Bahamas,122,176,51,6.3,NaN
12,Bahrain,42,63,7,2.0,AS
13,Bangladesh,0,0,0,0.0,AS
14,Barbados,143,173,36,6.3,NaN