# How do I merge DataFrames in pandas?

In [2]:
import pandas as pd

## Movies

In [5]:
movie_cols = ['movie_id', 'title']
movies = pd.read_table('u.item', sep='|', header=None, names=movie_cols, usecols=[0,1], encoding='ISO-8859-1')
movies.head()

   movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [6]:
movies.shape

(1682, 2)

In [7]:
movies.movie_id.nunique()

1682

## Ratings

In [12]:
rating_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('u.data', sep='\t', header=None, names=rating_cols, usecols=[0,1,2,3], encoding='ISO-8859-1')
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [10]:
ratings.shape

(100000, 2)

In [14]:
ratings.movie_id.nunique()

1682

In [15]:
ratings.loc[ratings.movie_id == 1, :].head()

      user_id  movie_id  rating  timestamp
24        308         1       4  887736532
454       287         1       5  875334088
957       148         1       4  877019411
971       280         1       4  891700426
1324       66         1       3  883601324

## Merging Movies and Ratings

In [16]:
# first we must know which columns are in each dataframe
movies.columns

Index(['movie_id', 'title'], dtype='object')

In [17]:
ratings.columns

Index(['user_id', 'movie_id', 'rating', 'timestamp'], dtype='object')

In [18]:
movie_ratings = pd.merge(movies, ratings)
movie_ratings.columns

Index(['movie_id', 'title', 'user_id', 'rating', 'timestamp'], dtype='object')

In [19]:
movie_ratings.head()

   movie_id             title  user_id  rating  timestamp
0         1  Toy Story (1995)      308       4  887736532
1         1  Toy Story (1995)      287       5  875334088
2         1  Toy Story (1995)      148       4  877019411
3         1  Toy Story (1995)      280       4  891700426
4         1  Toy Story (1995)       66       3  883601324

In [20]:
movie_ratings.shape

(100000, 5)

## Now, What if the columns you want to join on don't have the same name?

In [21]:
movies.columns = ['m_id', 'title']
movies.columns

Index(['m_id', 'title'], dtype='object')

In [22]:
ratings.columns

Index(['user_id', 'movie_id', 'rating', 'timestamp'], dtype='object')

In [24]:
pd.merge(movies, ratings, left_on='m_id', right_on='movie_id').head()

   m_id             title  user_id  movie_id  rating  timestamp
0     1  Toy Story (1995)      308         1       4  887736532
1     1  Toy Story (1995)      287         1       5  875334088
2     1  Toy Story (1995)      148         1       4  877019411
3     1  Toy Story (1995)      280         1       4  891700426
4     1  Toy Story (1995)       66         1       3  883601324

## What if you want to join on one index?

In [25]:
movies = movies.set_index('m_id')
movies.head()

                  title
m_id
1      Toy Story (1995)
2      GoldenEye (1995)
3     Four Rooms (1995)
4     Get Shorty (1995)
5        Copycat (1995)

In [27]:
pd.merge(movies, ratings, left_index=True, right_on='movie_id').head()

                 title  user_id  movie_id  rating  timestamp
24    Toy Story (1995)      308         1       4  887736532
454   Toy Story (1995)      287         1       5  875334088
957   Toy Story (1995)      148         1       4  877019411
971   Toy Story (1995)      280         1       4  891700426
1324  Toy Story (1995)       66         1       3  883601324