# Grouping and Aggregating - Analyzing and Exploring Data

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname')

C:\Users\Maryam\AppData\Local\Temp\ipykernel_4236\3211394593.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')

In [10]:
pd.set_option('display.max_columns', 171)
pd.set_option('display.max_rows', 171)
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [5]:
df['ConvertedCompYearly'].head(15)

ResponseId
1      61256.0
2     104413.0
3      53061.0
4      36197.0
5      60000.0
6     120000.0
7       6240.0
8      72000.0
9      70000.0
10      5400.0
11     65691.0
12     14400.0
13      1099.0
14         NaN
15         NaN
Name: ConvertedCompYearly, dtype: float64

In [7]:
df['ConvertedCompYearly'].median()

np.float64(75320.0)

In [9]:
# if we just run df.median, give median of all columns with numeric vlues
df.median(numeric_only=True)

WorkExp                    10.0
YearsCode                  14.0
TechEndorse_1               9.0
TechEndorse_2               4.0
TechEndorse_3               4.0
TechEndorse_4               6.0
TechEndorse_5               4.0
TechEndorse_6               5.0
TechEndorse_7               7.0
TechEndorse_8               4.0
TechEndorse_9               4.0
TechEndorse_13             10.0
TechOppose_1                9.0
TechOppose_2                4.0
TechOppose_3                6.0
TechOppose_5                5.0
TechOppose_7                4.0
TechOppose_9                3.0
TechOppose_11               4.0
TechOppose_13               5.0
TechOppose_16               6.0
TechOppose_15              10.0
JobSatPoints_1              6.0
JobSatPoints_2              4.0
JobSatPoints_3              7.0
JobSatPoints_4             10.0
JobSatPoints_5             10.0
JobSatPoints_6              8.0
JobSatPoints_7              5.0
JobSatPoints_8              7.0
JobSatPoints_9              6.0
JobSatPoints_10             7.0
JobSatPoints_11             5.0
JobSatPoints_13             9.0
JobSatPoints_14             9.0
JobSatPoints_15            15.0
JobSatPoints_16             8.0
ToolCountWork               6.0
ToolCountPersonal           5.0
CompTotal              105000.0
SO_Actions_1                5.0
SO_Actions_16               2.0
SO_Actions_3                6.0
SO_Actions_4                4.0
SO_Actions_5                5.0
SO_Actions_6                5.0
SO_Actions_9                6.0
SO_Actions_7                5.0
SO_Actions_10               8.0
SO_Actions_15              10.0
ConvertedCompYearly     75320.0
JobSat                      8.0
dtype: float64

In [11]:
df.describe() # give more info about numric columns

,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,27611.000000,25582.000000,2.486600e+04,26260.000000,24340.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,4.370841,4.431661,9.854315,8.307948,4.524067,5.925567,4.991710,4.048980,3.799323,4.365831,5.059867,5.508538,9.945766,6.867738,5.216173,7.455719,9.537947,9.758209,8.194965,5.884096,7.367799,6.744658,7.512569,5.703283,8.563324,8.679349,14.687487,7.826685,17.734852,8.545579,2.234198e+70,4.907845,3.339770,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,2.357058,2.620901,1.975692,2.202164,2.282867,2.301937,2.294707,2.607443,2.499468,2.557152,2.533541,2.906146,2.087463,3.741490,3.660632,3.726759,3.781286,3.557588,3.801257,3.900813,4.118532,3.888845,3.847265,4.110528,3.545288,3.633175,1.898188,4.077460,269.810134,44.664738,3.523096e+72,2.682204,2.411404,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,2.000000,10.000000,8.000000,3.000000,4.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,10.000000,4.000000,2.000000,4.000000,7.000000,7.000000,5.000000,2.000000,4.000000,3.000000,4.000000,2.000000,6.000000,6.000000,15.000000,4.000000,4.000000,3.000000,5.500000e+04,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,4.000000,10.000000,9.000000,4.000000,6.000000,5.000000,4.000000,3.000000,4.000000,5.000000,6.000000,10.000000,6.000000,4.000000,7.000000,10.000000,10.000000,8.000000,5.000000,7.000000,6.000000,7.000000,5.000000,9.000000,9.000000,15.000000,8.000000,6.000000,5.000000,1.050000e+05,5.000000,2.000000,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,7.000000,10.000000,9.000000,6.000000,8.000000,7.000000,6.000000,6.000000,6.000000,7.000000,8.000000,10.000000,10.000000,8.000000,11.000000,13.000000,13.000000,11.000000,9.000000,11.000000,10.000000,11.000000,9.000000,12.000000,12.000000,15.000000,11.000000,10.000000,7.000000,2.400000e+05,7.000000,5.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,16.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,10000.000000,1000.000000,5.555556e+74,15.000000,10.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [18]:
df.transpose().describe() # swaps rows ↔ columns.

ResponseId,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,...,49107,49108,49109,49110,49111,49112,49113,49114,49115,49116,49117,49118,49119,49120,49121,49122,49123,49124,49125,49126,49127,49128,49129,49130,49131,49132,49133,49134,49135,49136,49137,49138,49139,49140,49141,49142,49143,49144,49145,49146,49147,49148,49149,49150,49151,49152,49153,49154,49155,49156,49157,49158,49159,49160,49161,49162,49163,49164,49165,49166,49167,49168,49169,49170,49171,49172,49173,49174,49175,49176,49177,49178,49179,49180,49181,49182,49183,49184,49185,49186,49187,49188,49189,49190,49191
count,117,125,134.0,121.0,125,127.0,98,130,85.0,81,124,81,99,61.0,94,125,80,118,97,98,63,90,124,119,89,129,112,113,119,114,91,97,83,103,104.0,98,123,100.0,95,107.0,117,129,126.0,105.0,95.0,122,45,106.0,134,136,109,115.0,103,114,95,105,91,125,123,126,107,116,120.0,110,110.0,104,120,132,59,112,62,91,113,128,129.0,82,120,103,85.0,122.0,70,112,134,124,131,...,112,2,16.0,37.0,15,45.0,16,33.0,36.0,15,11,2,55.0,15,8,101.0,43.0,126,135.0,119,77,95,116.0,118,128,126,61,84,119,122.0,107,123,100,123,41,115,102.0,127,103,125.0,2,8,8,61.0,6,37.0,19,11,73.0,88.0,11,21,2,6,2,21,6,7,9,6,7,2,38.0,7,6,7,10,7,2,143.0,103.0,112,111,115,114,4,2,38.0,9,4,4,9,74.0,9,11
unique,76,70,82.0,75.0,74,77.0,62,85,49.0,60,76,62,64,37.0,58,82,55,74,65,61,47,62,75,71,53,77,72,67,80,73,76,68,55,64,62.0,80,84,60.0,63,66.0,74,75,88.0,65.0,59.0,70,40,75.0,90,85,71,71.0,74,73,64,77,61,77,73,72,66,82,69.0,78,75.0,66,76,83,52,73,55,52,67,75,78.0,61,69,72,48.0,76.0,51,65,87,70,82,...,67,2,15.0,25.0,15,30.0,16,21.0,25.0,15,11,2,32.0,15,8,64.0,31.0,85,85.0,83,59,63,70.0,79,71,82,50,57,76,78.0,77,82,69,74,32,60,68.0,82,73,78.0,2,8,8,38.0,6,25.0,19,10,50.0,63.0,10,21,2,6,2,20,6,7,9,6,7,2,26.0,7,6,7,10,7,2,92.0,62.0,75,71,68,68,4,2,26.0,9,4,4,9,53.0,9,10
top,Yes,Yes,3.0,5.0,Yes,5.0,Yes,Yes,9.0,No,Yes,No,No,6.0,No,5,No,Yes,Yes,No,No,No,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,8.0,Yes,Yes,10.0,Yes,2.0,Yes,Yes,8.0,8.0,4.0,Yes,Cassandra;Elasticsearch,2.0,Yes,Yes,Yes,15.0,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,2.0,Yes,5.0,No,Yes,Yes,Yes,Yes,Yes,No,No,Yes,8.0,No,Yes,Yes,13.0,4.0,Yes,No,Yes,Yes,Yes,...,Yes,"I am not primarily a developer, but I write co...",8.0,3.0,I work with developers or my work supports dev...,1.0,"I am not primarily a developer, but I write co...",2.0,6.0,"I used to be a developer by profession, but no...",I am a developer by profession,I am a developer by profession,9.0,I am a developer by profession,I am a developer by profession,10.0,10.0,Yes,9.0,Yes,No,Yes,7.0,Yes,Yes,Yes,Yes,Yes,Yes,8.0,Yes,Yes,Yes,Yes,No,Yes,7.0,Yes,Yes,10.0,I am a developer by profession,"I am not primarily a developer, but I write co...",I am a developer by profession,10.0,"I am not primarily a developer, but I write co...",7.0,I code primarily as a hobby,Student,6.0,8.0,Student,I am a developer by profession,I am a developer by profession,I am a developer by profession,I am a developer by profession,No,I am a developer by profession,I am a developer by profession,I am a developer by profession,I am a developer by profession,I am a developer by profession,I am a developer by profession,7.0,I am learning to code,I am learning to code,I am a developer by profession,I am learning to code,I am a developer by profession,I am learning to code,4.0,5.0,Yes,Yes,Yes,No,I am a developer by profession,I am a developer by profession,2.0,"I am not primarily a developer, but I write co...",I am a developer by profession,I code primarily as a hobby,I am a developer by profession,9.0,I am a developer by profession,Student
freq,6,6,6.0,5.0,6,6.0,5,9,5.0,5,7,5,5,6.0,6,8,9,7,6,5,6,6,6,7,7,7,6,5,5,7,6,6,5,6,5.0,8,7,5.0,7,6.0,7,8,5.0,5.0,4.0,6,3,5.0,7,7,7,4.0,7,7,7,5,5,7,6,7,7,6,5.0,7,5.0,5,7,7,5,6,5,6,6,8,8.0,4,7,7,4.0,5.0,5,7,7,7,7,...,6,1,2.0,3.0,1,5.0,1,3.0,3.0,1,1,1,4.0,1,1,4.0,3.0,7,5.0,6,5,8,6.0,6,6,7,6,5,6,7.0,6,6,7,7,7,8,5.0,7,7,6.0,1,1,1,5.0,1,3.0,1,2,4.0,5.0,2,1,1,1,1,2,1,1,1,1,1,1,3.0,1,1,1,1,1,1,6.0,7.0,5,7,7,7,1,1,4.0,1,1,1,1,4.0,1,2

In [19]:
df.describe().T # this show rows names

,count,mean,std,min,25%,50%,75%,max
WorkExp,42893.0,1.336740e+01,1.080012e+01,1.0,5.0,10.0,20.0,1.000000e+02
YearsCode,43042.0,1.657086e+01,1.178761e+01,1.0,8.0,14.0,24.0,1.000000e+02
TechEndorse_1,35975.0,7.867352e+00,2.397432e+00,1.0,7.0,9.0,9.0,1.400000e+01
TechEndorse_2,35975.0,4.104211e+00,2.275821e+00,1.0,2.0,4.0,6.0,1.400000e+01
TechEndorse_3,35975.0,4.110271e+00,2.329536e+00,1.0,2.0,4.0,6.0,1.400000e+01
TechEndorse_4,35975.0,5.678193e+00,2.398084e+00,1.0,4.0,6.0,8.0,1.400000e+01
TechEndorse_5,35975.0,4.119388e+00,2.437945e+00,1.0,2.0,4.0,6.0,1.400000e+01
TechEndorse_6,35975.0,5.225990e+00,2.801045e+00,1.0,3.0,5.0,8.0,1.400000e+01
TechEndorse_7,35975.0,6.477387e+00,2.331468e+00,1.0,5.0,7.0,8.0,1.400000e+01
TechEndorse_8,35975.0,4.370841e+00,2.357058e+00,1.0,2.0,4.0,6.0,1.400000e+01
TechEndorse_9,35975.0,4.431661e+00,2.620901e+00,1.0,2.0,4.0,7.0,1.400000e+01
TechEndorse_13,35975.0,9.854315e+00,1.975692e+00,1.0,10.0,10.0,10.0,1.400000e+01
TechOppose_1,34259.0,8.307948e+00,2.202164e+00,1.0,8.0,9.0,9.0,1.500000e+01
TechOppose_2,34259.0,4.524067e+00,2.282867e+00,1.0,3.0,4.0,6.0,1.500000e+01
TechOppose_3,34259.0,5.925567e+00,2.301937e+00,1.0,4.0,6.0,8.0,1.500000e+01
TechOppose_5,34259.0,4.991710e+00,2.294707e+00,1.0,3.0,5.0,7.0,1.500000e+01
TechOppose_7,34259.0,4.048980e+00,2.607443e+00,1.0,2.0,4.0,6.0,1.500000e+01
TechOppose_9,34259.0,3.799323e+00,2.499468e+00,1.0,2.0,3.0,6.0,1.500000e+01
TechOppose_11,34259.0,4.365831e+00,2.557152e+00,1.0,2.0,4.0,6.0,1.400000e+01
TechOppose_13,34259.0,5.059867e+00,2.533541e+00,1.0,3.0,5.0,7.0,1.500000e+01
TechOppose_16,34259.0,5.508538e+00,2.906146e+00,1.0,3.0,6.0,8.0,1.500000e+01
TechOppose_15,34259.0,9.945766e+00,2.087463e+00,1.0,10.0,10.0,10.0,1.600000e+01
JobSatPoints_1,24943.0,6.867738e+00,3.741490e+00,1.0,4.0,6.0,10.0,1.500000e+01
JobSatPoints_2,24943.0,5.216173e+00,3.660632e+00,1.0,2.0,4.0,8.0,1.500000e+01
JobSatPoints_3,24943.0,7.455719e+00,3.726759e+00,1.0,4.0,7.0,11.0,1.500000e+01
JobSatPoints_4,24943.0,9.537947e+00,3.781286e+00,1.0,7.0,10.0,13.0,1.500000e+01
JobSatPoints_5,24943.0,9.758209e+00,3.557588e+00,1.0,7.0,10.0,13.0,1.500000e+01
JobSatPoints_6,24943.0,8.194965e+00,3.801257e+00,1.0,5.0,8.0,11.0,1.500000e+01
JobSatPoints_7,24943.0,5.884096e+00,3.900813e+00,1.0,2.0,5.0,9.0,1.500000e+01
JobSatPoints_8,24943.0,7.367799e+00,4.118532e+00,1.0,4.0,7.0,11.0,1.500000e+01
JobSatPoints_9,24943.0,6.744658e+00,3.888845e+00,1.0,3.0,6.0,10.0,1.500000e+01
JobSatPoints_10,24943.0,7.512569e+00,3.847265e+00,1.0,4.0,7.0,11.0,1.500000e+01
JobSatPoints_11,24943.0,5.703283e+00,4.110528e+00,1.0,2.0,5.0,9.0,1.500000e+01
JobSatPoints_13,24943.0,8.563324e+00,3.545288e+00,1.0,6.0,9.0,12.0,1.500000e+01
JobSatPoints_14,24943.0,8.679349e+00,3.633175e+00,1.0,6.0,9.0,12.0,1.500000e+01
JobSatPoints_15,24943.0,1.468749e+01,1.898188e+00,1.0,15.0,15.0,15.0,1.500000e+01
JobSatPoints_16,24943.0,7.826685e+00,4.077460e+00,1.0,4.0,8.0,11.0,1.500000e+01
ToolCountWork,27611.0,1.773485e+01,2.698101e+02,0.0,4.0,6.0,10.0,1.000000e+04
ToolCountPersonal,25582.0,8.545579e+00,4.466474e+01,0.0,3.0,5.0,7.0,1.000000e+03
CompTotal,24866.0,2.234198e+70,3.523096e+72,0.0,55000.0,105000.0,240000.0,5.555556e+74
SO_Actions_1,26260.0,4.907845e+00,2.682204e+00,1.0,3.0,5.0,7.0,1.500000e+01
SO_Actions_16,24340.0,3.339770e+00,2.411404e+00,1.0,1.0,2.0,5.0,1.000000e+01
SO_Actions_3,26260.0,5.718355e+00,2.628016e+00,1.0,3.0,6.0,8.0,1.500000e+01
SO_Actions_4,26260.0,4.561767e+00,3.070548e+00,1.0,1.0,4.0,7.0,1.500000e+01
SO_Actions_5,26260.0,4.790861e+00,2.643177e+00,1.0,3.0,5.0,7.0,1.500000e+01
SO_Actions_6,26260.0,5.199657e+00,2.563562e+00,1.0,3.0,5.0,7.0,1.500000e+01
SO_Actions_9,26260.0,5.676314e+00,2.310659e+00,1.0,4.0,6.0,7.0,1.500000e+01
SO_Actions_7,26260.0,4.984653e+00,2.490095e+00,1.0,3.0,5.0,7.0,1.500000e+01
SO_Actions_10,26260.0,7.099505e+00,2.469394e+00,1.0,6.0,8.0,9.0,1.500000e+01
SO_Actions_15,26260.0,1.007928e+01,1.940928e+00,1.0,10.0,10.0,10.0,1.500000e+01
ConvertedCompYearly,23947.0,1.017615e+05,4.617569e+05,1.0,38171.0,75320.0,120596.0,5.000000e+07
JobSat,26670.0,7.201950e+00,1.997245e+00,0.0,6.0,8.0,8.0,1.000000e+01

In [20]:
# count values
df['ConvertedCompYearly'].count()

np.int64(23947)

In [21]:
df['CommPlatformHaveEntr']

ResponseId
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
        ...
49187    NaN
49188    NaN
49189    NaN
49190    NaN
49191    NaN
Name: CommPlatformHaveEntr, Length: 49191, dtype: object

In [22]:
schema_df.loc['CommPlatformHaveEntr']

qid                                                     QID66
question    Was the community platform you use not listed ...
type                                                       TE
sub                                                       NaN
sq_id                                                     NaN
Name: CommPlatformHaveEntr, dtype: object

In [23]:
df['CommPlatformHaveEntr'].value_counts()

CommPlatformHaveEntr
Mastodon                        250
mastodon                         53
Discourse                        30
Telegram                         27
lobste.rs                        26
                               ...
Nothing use                       1
lemmy.world, programming.dev      1
ServiceNow                        1
Good                              1
Daily.Dev, ActualLab              1
Name: count, Length: 675, dtype: int64

In [24]:
# to get a percentage
df['CommPlatformHaveEntr'].value_counts(normalize=True)

CommPlatformHaveEntr
Mastodon                        0.169377
mastodon                        0.035908
Discourse                       0.020325
Telegram                        0.018293
lobste.rs                       0.017615
                                  ...
Nothing use                     0.000678
lemmy.world, programming.dev    0.000678
ServiceNow                      0.000678
Good                            0.000678
Daily.Dev, ActualLab            0.000678
Name: proportion, Length: 675, dtype: float64

In [6]:
df['Country'].value_counts()

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
Lesotho                                                    1
Djibouti                                                   1
Cape Verde                                                 1
Palau                                                      1
Guinea                                                     1
Name: count, Length: 177, dtype: int64

In [7]:
# to group result by country
df.groupby(['Country']) # we got DataFrameGroupBy object

In [11]:
# assign to a variable
country_grp = df.groupby(['Country'])
country_grp.get_group('Germany') # we see it return a dataframe

C:\Users\Maryam\AppData\Local\Temp\ipykernel_4236\845583521.py:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('Germany') # we see it return a dataframe

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
19,I am a developer by profession,35-44 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,20.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",NaN,20.0,"Developer, back-end",20 to 99 employees,People manager,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,14.0,6.0,5.0,1.0,2.0,4.0,12.0,3.0,10.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,4.0,3.0,13.0,6.0,7.0,8.0,9.0,2.0,10.0,14.0,1.0,11.0,12.0,15.0,5.0,NaN,No,I have somewhat considered changing my career ...,2.0,1.0,Germany,EUR European Euro,NaN,Yes,Bash/Shell (all shells);Java;JavaScript;Perl;T...,Bash/Shell (all shells);Java,Bash/Shell (all shells);Java,NaN,NaN,Yes,H2;MongoDB;MySQL;PostgreSQL,MongoDB;PostgreSQL,MongoDB;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Ansible;APT;Docker;H...,Amazon Web Services (AWS);Docker;Maven (build ...,Amazon Web Services (AWS);Docker;Maven (build ...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,IntelliJ IDEA;Vim,IntelliJ IDEA;Vim,IntelliJ IDEA;Vim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ubuntu;Debian,Ubuntu;Debian,GitHub;Google Workspace;Wikis,GitHub;Google Workspace;Wikis,GitHub;Google Workspace;Wikis,NaN,NaN,Stack Overflow;Discord;Reddit,Stack Overflow;Discord;Reddit,Stack Overflow;Discord;Reddit,NaN,NaN,Yes,DeepSeek (R- Reasoning models);DeepSeek (V- Ge...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,Less than once every 2 - 3 months,Long-form articles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,Very poor at handling complex tasks,NaN,Learning about a codebase;Project planning;Doc...,Writing code;Predictive analytics;Learning new...,NaN,NaN,Other (write in):,No,"No, and I don't plan to","No, but my development work has changed somewh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,AI will not become more capable in 3-5 years.,NaN,5.0
36,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,10.0,"Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools for...",Colleague or on-the-job training,10.0,"Developer, back-end","1,000 to 4,999 employees",Individual contributor,"Your choice (very flexible, you can come in wh...",No,Work,3.0,8.0,2.0,11.0,7.0,5.0,4.0,1.0,12.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Higher Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have somewhat considered changing my career ...,4.0,6.0,Germany,EUR European Euro,82000.0,Yes,Bash/Shell (all shells);HTML/CSS;JavaScript;SQ...,Bash/Shell (all shells);HTML/CSS;TypeScript,Bash/Shell (all shells);HTML/CSS;TypeScript,NaN,NaN,Yes,Dynamodb;Elasticsearch;MySQL;PostgreSQL;Redis,Dynamodb;MySQL;PostgreSQL;Redis,Dynamodb;MySQL;PostgreSQL;Redis,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Digital Ocea...,Amazon Web Services (AWS);Datadog;Digital Ocea...,Amazon Web Services (AWS);Datadog;Digital Ocea...,NaN,NaN,Yes,Express;Fastify;NestJS;Next.js;Node.js;React;V...,NestJS;Node.js,NestJS;Node.js,NaN,NaN,Yes,Cursor;IntelliJ IDEA;Visual Studio,Cursor;IntelliJ IDEA,Cursor;IntelliJ IDEA,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows;MacOS,MacOS,Clickup;Confluence;GitHub;GitLab;Jira;Lucid (i...,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,NaN,NaN,Yes,Less than once per month or monthly,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",More than half the time,"Yes, I use AI tools daily",Very favorable,Somewhat trust,"Good, but not great at handling complex tasks",Project planning;Writing code;Debugging or fix...,Committing and reviewing code,Testing code;Deployment and monitoring;Learnin...,Learning about a codebase;Creating or maintain...,Documenting code;Search for answers,"AI solutions that are almost right, but not qu...",yes,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering,Language processing,AI agents have helped me automate repetitive t...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,AI agents have increased my productivity.;AI a...,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,Redis;ChromaDB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,problem solving,95132.0,6.0
51,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,19.0,"Developer, game or graphics",Less than 20 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,1.0,8.0,7.0,10.0,12.0,11.0,2.0,14.0,NaN,11.0,9.0,7.0,3.0,1.0,8.0,4.0,10.0,5.0,15.0,NaN,Software Development,5.0,4.0,14.0,13.0,3.0,9.0,2.0,11.0,12.0,10.0,1.0,7.0,8.0,15.0,6.0,NaN,Yes,I have strongly considered changing my career ...,10.0,NaN,Germany,EUR European Euro,65000.0,Yes,C#;JavaScript,NaN,NaN,NaN,NaN,Yes,Cloud Firestore;Firebase Realtime Database,NaN,NaN,NaN,NaN,Yes,Google Cloud,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Cursor;VSCodium;Windsurf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,MacOS,Asana;GitHub;Notion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models),NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Lists of recommendat...,7.0,NaN,11.0,9.0,3.0,4.0,13.0,1.0,6.0,15.0,NaN,"No, not really",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,"Good, but not great at handling complex tasks",Writing code,Project planning;Testing code;Committing and r...,Documenting code,Learning about a codebase,Debugging or fixing code;Search for answers;Le...,"AI solutions that are almost right, but not qu...","Yes, it's mandatory to be when you have ridicu...","No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,I am concerned about the accuracy of the infor...,NaN,I have concerns about the security and privacy...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I’m stuck...,"Soft skills, and the capacity to have complete...",75410.0,6.0
72,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Attending school (full-time);Engaged in paid w...,3.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,13.0,"Developer, embedded applications or devices","Just me - I am a freelancer, sole proprietor, ...",Individual contributor,Remote,No,Work,13.0,5.0,4.0,9.0,2.0,1.0,7.0,12.0,3.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,4.0,6.0,7.0,8.0,2.0,9.0,10.0,3.0,11.0,12.0,13.0,14.0,15.0,5.0,NaN,No,I have transitioned into a new career and/or i...,5.0,5.0,Germany,EUR European Euro,NaN,Yes,Assembly;C;C++;Python,Assembly;C;C++,Assembly;C;C++,"Nim, Answer set programming (ASP), System Verilog","Nim, Answer set programming (ASP), System Verilog",No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fedora,Fedora,GitHub;GitLab,GitHub;GitLab,GitHub;GitLab,NaN,NaN,Stack Overflow;Discord;Reddit;GitHub (public p...,Stack Overflow;Discord;Reddit;GitHub (public p...,Stack Overflow;Discord;Reddit;GitHub (public p...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 3 and 5 years,"Infrequently, less than once per year",NaN,1.0,NaN,7.0,9.0,6.0,14.0,2.0,4.0,8.0,15.0,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Unfavorable,Somewhat distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
99,"I am not primarily a developer, but I write co...",18-24 years old,"Secondary school (e.g. American high school, G...",Student,Attending school (full-time),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,4.0,Student,NaN,NaN,NaN,NaN,Work,13.0,1.0,11.0,8.0,7.0,5.0,10.0,6.0,3.0,14.0,NaN,14.0,1.0,3.0,6.0,2.0,7.0,5.0,8.0,13.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have neither consider or transitioned into a...,5.0,1.0,Germany,EUR European Euro,0.0,Yes,Assembly;C;C++;Python,C;C++;HTML/CSS;Java;JavaScript;Python,C;C++;Python,VHDL,Verilog,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Node.js,React,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,c++23,c++23,c++23,NaN,NaN,Windows;Android,Windows Subsystem for Linux (WSL),GitHub,GitHub,GitHub,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Stack Overflow;Stack Exchange;Discord;GitHub (...,Stack Overflow;Stack Exchange;Discord;GitHub (...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 1 and 3 years,Less than once every 2 - 3 months,Coding challenges;Job board,12.0,NaN,10.0,14.0,1.0,6.0,4.0,5.0,7.0,15.0,NaN,"No, not really",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,Search for answers,Learning about a codebase;Writing code;Documen...,Project planning;Committing and reviewing code...,NaN,NaN,It’s hard to understand how or why the code works,No and it should never,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,I am concerned about the accuracy of the infor...,I have concerns about the security and privacy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Writing secure code,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48990,"I used to be a developer by profession, but no...",55-64 years old,Other (please specify):,Employed,None of the above,26.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,43.0,"Architect, software or solutions",100 to 499 employees,People manager,"Your choice (very flexible, you can come in wh...",No,Work,8.0,5.0,2.0,7.0,1.0,6.0,9.0,4.0,3.0,10.0,NaN,8.0,2.0,9.0,7.0,5.0,1.0,6.0,4.0,3.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,6.0,3.0,Germany,EUR European Euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Generating content or synthetic data,Testing code,Deployment and monitoring,Learning about a codebase;Project planning;Wri...,Search for answers,"AI solutions that are almost right, but not qu...",no,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;Business process automati...,NaN,AI agents have helped me automate repetitive t...,AI agents have helped me solve complex problem...,AI agents have improved collaboration within m...,AI agents have increased my productivity.,AI agents have improved the quality of my code.,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,Grafana + Prometheus,NaN,ChatGPT;GitHub Copilot;Google Gemini;Microsoft...,NaN,When I don’t trust AI’s answers;When I want to...,"abstract and analytic thinking, understanding ...",NaN,NaN
49001,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Your choice (very flexible, you can come in wh...",No,Work,8.0,5.0,1.0,7.0,4.0,3.0,9.0,6.0,2.0,10.0,NaN,9.0,8.0,4.0,10.0,1.0,2.0,7.0,6.0,5.0,3.0,bad docs,Software Development,10.0,2.0,7.0,8.0,14.0,13.0,9.0,3.0,1.0,6.0,5.0,11.0,12.0,15.0,4.0,NaN,No,I have somewhat considered changing my career ...,3.0,1.0,Germany,EUR European Euro,65000.0,Yes,Java;JavaScript;Kotlin;TypeScript,NaN,NaN,NaN,NaN,Yes,MongoDB,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Gradle;npm;Te...,Docker;Kubernetes;Terraform,Docker;Terraform,NaN,NaN,Yes,Node.js;React,NaN,NaN,NaN,NaN,Yes,Android Studio;IntelliJ IDEA;Visual Studio Code,Android Studio;IntelliJ IDEA;Jupyter Notebook/...,Android Studio;IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Ubuntu;Android,Ubuntu;Android,Asana;Coda;GitHub;Markdown File;Notion;Obsidia...,GitHub;Markdown File;Obsidian;Stack Overflow f...,GitHub;Markdown File;Obsidian,NaN,NaN,Stack Overflow;Stack Exchange;Reddit;Hacker Ne...,Stack Overflow;Stack Exchange;Hacker News;GitH...,Stack Overflow;Stack Exchange;Hacker News;GitH...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,Less than once every 2 - 3 months,Long-form articles;Coding challenges;Logic gam...,5.0,1.0,7.0,9.0,6.0,4.0,3.0,2.0,8.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Favorable,Somewhat distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Learnin...,Committing and reviewing code;Predictive analy...,Project planning;Documenting code;Debugging or...,NaN,NaN,"AI solutions that are almost right, but not qu...","Yeah but for MVP type stuff, not for production","No, and I don't plan to","Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,NaN,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Problem solving skills. If people use AI for e...,75410.0,7.0

In [13]:
# as we did before to got coutries using filter, we will face same result
filt = df['Country'] == 'Germany'
df.loc[filt]

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
19,I am a developer by profession,35-44 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,20.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",NaN,20.0,"Developer, back-end",20 to 99 employees,People manager,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,14.0,6.0,5.0,1.0,2.0,4.0,12.0,3.0,10.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,4.0,3.0,13.0,6.0,7.0,8.0,9.0,2.0,10.0,14.0,1.0,11.0,12.0,15.0,5.0,NaN,No,I have somewhat considered changing my career ...,2.0,1.0,Germany,EUR European Euro,NaN,Yes,Bash/Shell (all shells);Java;JavaScript;Perl;T...,Bash/Shell (all shells);Java,Bash/Shell (all shells);Java,NaN,NaN,Yes,H2;MongoDB;MySQL;PostgreSQL,MongoDB;PostgreSQL,MongoDB;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);Ansible;APT;Docker;H...,Amazon Web Services (AWS);Docker;Maven (build ...,Amazon Web Services (AWS);Docker;Maven (build ...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,IntelliJ IDEA;Vim,IntelliJ IDEA;Vim,IntelliJ IDEA;Vim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ubuntu;Debian,Ubuntu;Debian,GitHub;Google Workspace;Wikis,GitHub;Google Workspace;Wikis,GitHub;Google Workspace;Wikis,NaN,NaN,Stack Overflow;Discord;Reddit,Stack Overflow;Discord;Reddit,Stack Overflow;Discord;Reddit,NaN,NaN,Yes,DeepSeek (R- Reasoning models);DeepSeek (V- Ge...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,Less than once every 2 - 3 months,Long-form articles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,Very poor at handling complex tasks,NaN,Learning about a codebase;Project planning;Doc...,Writing code;Predictive analytics;Learning new...,NaN,NaN,Other (write in):,No,"No, and I don't plan to","No, but my development work has changed somewh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,AI will not become more capable in 3-5 years.,NaN,5.0
36,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,10.0,"Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps,"Yes, I learned how to use AI-enabled tools for...",Colleague or on-the-job training,10.0,"Developer, back-end","1,000 to 4,999 employees",Individual contributor,"Your choice (very flexible, you can come in wh...",No,Work,3.0,8.0,2.0,11.0,7.0,5.0,4.0,1.0,12.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Higher Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have somewhat considered changing my career ...,4.0,6.0,Germany,EUR European Euro,82000.0,Yes,Bash/Shell (all shells);HTML/CSS;JavaScript;SQ...,Bash/Shell (all shells);HTML/CSS;TypeScript,Bash/Shell (all shells);HTML/CSS;TypeScript,NaN,NaN,Yes,Dynamodb;Elasticsearch;MySQL;PostgreSQL;Redis,Dynamodb;MySQL;PostgreSQL;Redis,Dynamodb;MySQL;PostgreSQL;Redis,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Digital Ocea...,Amazon Web Services (AWS);Datadog;Digital Ocea...,Amazon Web Services (AWS);Datadog;Digital Ocea...,NaN,NaN,Yes,Express;Fastify;NestJS;Next.js;Node.js;React;V...,NestJS;Node.js,NestJS;Node.js,NaN,NaN,Yes,Cursor;IntelliJ IDEA;Visual Studio,Cursor;IntelliJ IDEA,Cursor;IntelliJ IDEA,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows;MacOS,MacOS,Clickup;Confluence;GitHub;GitLab;Jira;Lucid (i...,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,NaN,NaN,Yes,Less than once per month or monthly,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",More than half the time,"Yes, I use AI tools daily",Very favorable,Somewhat trust,"Good, but not great at handling complex tasks",Project planning;Writing code;Debugging or fix...,Committing and reviewing code,Testing code;Deployment and monitoring;Learnin...,Learning about a codebase;Creating or maintain...,Documenting code;Search for answers,"AI solutions that are almost right, but not qu...",yes,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering,Language processing,AI agents have helped me automate repetitive t...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,AI agents have increased my productivity.;AI a...,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,Redis;ChromaDB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,problem solving,95132.0,6.0
51,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,10.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,19.0,"Developer, game or graphics",Less than 20 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,1.0,8.0,7.0,10.0,12.0,11.0,2.0,14.0,NaN,11.0,9.0,7.0,3.0,1.0,8.0,4.0,10.0,5.0,15.0,NaN,Software Development,5.0,4.0,14.0,13.0,3.0,9.0,2.0,11.0,12.0,10.0,1.0,7.0,8.0,15.0,6.0,NaN,Yes,I have strongly considered changing my career ...,10.0,NaN,Germany,EUR European Euro,65000.0,Yes,C#;JavaScript,NaN,NaN,NaN,NaN,Yes,Cloud Firestore;Firebase Realtime Database,NaN,NaN,NaN,NaN,Yes,Google Cloud,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Cursor;VSCodium;Windsurf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,MacOS,Asana;GitHub;Notion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models),NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Lists of recommendat...,7.0,NaN,11.0,9.0,3.0,4.0,13.0,1.0,6.0,15.0,NaN,"No, not really",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,"Good, but not great at handling complex tasks",Writing code,Project planning;Testing code;Committing and r...,Documenting code,Learning about a codebase,Debugging or fixing code;Search for answers;Le...,"AI solutions that are almost right, but not qu...","Yes, it's mandatory to be when you have ridicu...","No, but I plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,I am concerned about the accuracy of the infor...,NaN,I have concerns about the security and privacy...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I’m stuck...,"Soft skills, and the capacity to have complete...",75410.0,6.0
72,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Attending school (full-time);Engaged in paid w...,3.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,13.0,"Developer, embedded applications or devices","Just me - I am a freelancer, sole proprietor, ...",Individual contributor,Remote,No,Work,13.0,5.0,4.0,9.0,2.0,1.0,7.0,12.0,3.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,4.0,6.0,7.0,8.0,2.0,9.0,10.0,3.0,11.0,12.0,13.0,14.0,15.0,5.0,NaN,No,I have transitioned into a new career and/or i...,5.0,5.0,Germany,EUR European Euro,NaN,Yes,Assembly;C;C++;Python,Assembly;C;C++,Assembly;C;C++,"Nim, Answer set programming (ASP), System Verilog","Nim, Answer set programming (ASP), System Verilog",No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fedora,Fedora,GitHub;GitLab,GitHub;GitLab,GitHub;GitLab,NaN,NaN,Stack Overflow;Discord;Reddit;GitHub (public p...,Stack Overflow;Discord;Reddit;GitHub (public p...,Stack Overflow;Discord;Reddit;GitHub (public p...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 3 and 5 years,"Infrequently, less than once per year",NaN,1.0,NaN,7.0,9.0,6.0,14.0,2.0,4.0,8.0,15.0,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Unfavorable,Somewhat distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
99,"I am not primarily a developer, but I write co...",18-24 years old,"Secondary school (e.g. American high school, G...",Student,Attending school (full-time),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,4.0,Student,NaN,NaN,NaN,NaN,Work,13.0,1.0,11.0,8.0,7.0,5.0,10.0,6.0,3.0,14.0,NaN,14.0,1.0,3.0,6.0,2.0,7.0,5.0,8.0,13.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have neither consider or transitioned into a...,5.0,1.0,Germany,EUR European Euro,0.0,Yes,Assembly;C;C++;Python,C;C++;HTML/CSS;Java;JavaScript;Python,C;C++;Python,VHDL,Verilog,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Node.js,React,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,c++23,c++23,c++23,NaN,NaN,Windows;Android,Windows Subsystem for Linux (WSL),GitHub,GitHub,GitHub,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;G...,Stack Overflow;Stack Exchange;Discord;GitHub (...,Stack Overflow;Stack Exchange;Discord;GitHub (...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 1 and 3 years,Less than once every 2 - 3 months,Coding challenges;Job board,12.0,NaN,10.0,14.0,1.0,6.0,4.0,5.0,7.0,15.0,NaN,"No, not really",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,Search for answers,Learning about a codebase;Writing code;Documen...,Project planning;Committing and reviewing code...,NaN,NaN,It’s hard to understand how or why the code works,No and it should never,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,I am concerned about the accuracy of the infor...,I have concerns about the security and privacy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Writing secure code,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48990,"I used to be a developer by profession, but no...",55-64 years old,Other (please specify):,Employed,None of the above,26.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,43.0,"Architect, software or solutions",100 to 499 employees,People manager,"Your choice (very flexible, you can come in wh...",No,Work,8.0,5.0,2.0,7.0,1.0,6.0,9.0,4.0,3.0,10.0,NaN,8.0,2.0,9.0,7.0,5.0,1.0,6.0,4.0,3.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,6.0,3.0,Germany,EUR European Euro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Generating content or synthetic data,Testing code,Deployment and monitoring,Learning about a codebase;Project planning;Wri...,Search for answers,"AI solutions that are almost right, but not qu...",no,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;Business process automati...,NaN,AI agents have helped me automate repetitive t...,AI agents have helped me solve complex problem...,AI agents have improved collaboration within m...,AI agents have increased my productivity.,AI agents have improved the quality of my code.,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,Grafana + Prometheus,NaN,ChatGPT;GitHub Copilot;Google Gemini;Microsoft...,NaN,When I don’t trust AI’s answers;When I want to...,"abstract and analytic thinking, understanding ...",NaN,NaN
49001,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Your choice (very flexible, you can come in wh...",No,Work,8.0,5.0,1.0,7.0,4.0,3.0,9.0,6.0,2.0,10.0,NaN,9.0,8.0,4.0,10.0,1.0,2.0,7.0,6.0,5.0,3.0,bad docs,Software Development,10.0,2.0,7.0,8.0,14.0,13.0,9.0,3.0,1.0,6.0,5.0,11.0,12.0,15.0,4.0,NaN,No,I have somewhat considered changing my career ...,3.0,1.0,Germany,EUR European Euro,65000.0,Yes,Java;JavaScript;Kotlin;TypeScript,NaN,NaN,NaN,NaN,Yes,MongoDB,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Gradle;npm;Te...,Docker;Kubernetes;Terraform,Docker;Terraform,NaN,NaN,Yes,Node.js;React,NaN,NaN,NaN,NaN,Yes,Android Studio;IntelliJ IDEA;Visual Studio Code,Android Studio;IntelliJ IDEA;Jupyter Notebook/...,Android Studio;IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Ubuntu;Android,Ubuntu;Android,Asana;Coda;GitHub;Markdown File;Notion;Obsidia...,GitHub;Markdown File;Obsidian;Stack Overflow f...,GitHub;Markdown File;Obsidian,NaN,NaN,Stack Overflow;Stack Exchange;Reddit;Hacker Ne...,Stack Overflow;Stack Exchange;Hacker News;GitH...,Stack Overflow;Stack Exchange;Hacker News;GitH...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,Less than once every 2 - 3 months,Long-form articles;Coding challenges;Logic gam...,5.0,1.0,7.0,9.0,6.0,4.0,3.0,2.0,8.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Favorable,Somewhat distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Learnin...,Committing and reviewing code;Predictive analy...,Project planning;Documenting code;Debugging or...,NaN,NaN,"AI solutions that are almost right, but not qu...","Yeah but for MVP type stuff, not for production","No, and I don't plan to","Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,NaN,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Problem solving skills. If people use AI for e...,75410.0,7.0

In [14]:
# now if we want the most platforms using in this country using filter
filt = df['Country'] == 'Germany'
df.loc[filt]['CommPlatformHaveEntr'].value_counts()

CommPlatformHaveEntr
Mastodon                                                                        40
mastodon                                                                        12
Mattermost                                                                       6
lobste.rs                                                                        5
Matrix                                                                           5
daily.dev                                                                        4
Lobsters                                                                         3
Codeberg                                                                         3
Mastodon, Matrix                                                                 2
wonderful.dev                                                                    2
xing                                                                             2
Lemmy                                                                            2
users.rust-lang.org, internals.rust-lang.org                                     2
IRC                                                                              2
Lemmy, Mastodon                                                                  2
4chan                                                                            2
Mastodon, Fediverse                                                              2
Gotosocial                                                                       1
Codeberg, Forgejo, Mastodon, Discourse                                           1
Matrix (Element), Mastodon                                                       1
discourse, zulip, mastodon                                                       1
Mastodon, Lemmy                                                                  1
Fediverse, Mastodon, Matrix, Delta Chat                                          1
Mastodon,                                                                        1
Adobe Community                                                                  1
Tex Stackexchange                                                                1
Udemy                                                                            1
nostr                                                                            1
mastodon, ziggit                                                                 1
ziggit.dev                                                                       1
Codeberg, Mastodon, Pixelfed                                                     1
Zulip                                                                            1
elixirforum, mastodon                                                            1
Mattermost, Zoom                                                                 1
Elixir Forum                                                                     1
https://elixirforum.com/                                                         1
zoho                                                                             1
Element                                                                          1
GitLab,Zulip                                                                     1
mattermost,matrix/element                                                        1
personal talk                                                                    1
Mastodon, Viva Engage                                                            1
CodeBerg                                                                         1
private newsletters (not Substack)                                               1
Codidact, Mastodon, Fediverse                                                    1
Udemy, LeetCode                                                                  1
Fedi                                                                             1
mastodon,fediverse                                                               1
Community-Discourse-Forums                                                       1
Discourse, Matrix, Zulip                                                         1
Bluesky, Mastodon                                                                1
fediverse, rss, independent blogs                                                1
Fediverse/Mastodon                                                               1
Lobste.rs                                                                        1
Dev.to                                                                           1
coderberg                                                                        1
The Rust Programming Language Forum                                              1
WeLink                                                                           1
9gag                                                                             1
discourse, Xing                                                                  1
IRC, Mailing lists                                                               1
GitLab, KDE Invent                                                               1
Discourse                                                                        1
fedi                                                                             1
mastodon, infosec.social                                                         1
Mastodon,Sourcehut                                                               1
tildes                                                                           1
Threads, Instagram                                                               1
Delphi-Praxis                                                                    1
LWN                                                                              1
https://bbs.archlinux.org/                                                       1
Sourcehut                                                                        1
MIcrosoft Engange                                                                1
communitys own forum                                                             1
ada-lang.io                                                                      1
Mastodon, Matrix, Discourse                                                      1
Telegram, WhatsApp                                                               1
Discourse instance                                                               1
Xing                                                                             1
Usenet, mailing lists                                                            1
advent of code; perl weekly challenge; codewars                                  1
Fediverse                                                                        1
talk.jekyllrb.com                                                                1
DeltaChat                                                                        1
Mastodon, PeerTube, Fediverse                                                    1
mastodon, sharkey                                                                1
Wikipedia                                                                        1
asf                                                                              1
superuser                                                                        1
Zulip, Matrix                                                                    1
Guilded                                                                          1
Fosstodon                                                                        1
Mastodon, Computerbase, Heise, iced discourse                                    1
Forums                                                                           1
IRC, Matrix                                                                      1
bbs.archlinux.org                                                                1
Xing.com                                                                         1
fediverse                                                                        1
Julia discourse                                                                  1
Zulip,Discourse                                                                  1
GitLab                                                                           1
https://lobste.rs                                                                1
Typo3 Foren                                                                      1
Mastodon/Fediverse                                                               1
Lemmy,Mastodon                                                                   1
Discourse group                                                                  1
Threadyverse (Lemmy/Mbin/PieFed/...),Fediverse (Mastodon/Misskey/Akkoma/...)     1
Hugging Face                                                                     1
Suck my balls this takes too long!                                               1
codeberg                                                                         1
Discourse, GoToSocial                                                            1
Anypoint                                                                         1
Name: count, dtype: int64

In [16]:
# here we can see how to benifit from grouping, where groupby country directly help me to find these results
country_grp['CommPlatformHaveEntr'].value_counts().head(50)

Country    CommPlatformHaveEntr
Albania    word of nouth                             1
Algeria    Codeberg                                  1
           en.delphipraxis.net                       1
Angola     Ya                                        1
Argentina  Daily.dev                                 1
           Facebook                                  1
           Lobsters                                  1
           Mastodon                                  1
           Mastodon, Instagram                       1
Armenia    Mastodon, Matrix                          1
           lobsters                                  1
Australia  Mastodon                                 12
           Discourse                                 4
           Fediverse                                 2
           IRC                                       2
           Mastodon, Lobsters                        2
           0                                         1
           Arduino, Espressif                        1
           Atlassian Community                       1
           Bugzilla, Codeberg, Fossil                1
           Daily.Dev, ActualLab                      1
           Discord                                   1
           Elixir forum                              1
           Fediverse (e.g. Mastodon)                 1
           ForgeJo                                   1
           Gartner                                   1
           Google Maps, Local Guides,                1
           Linux Forum, Open Software Foundation     1
           Matrix, Discourse                         1
           Mattermost                                1
           Microsoft Power Platform Community        1
           Nostr, Mastodon                           1
           Others                                    1
           Tech Communities                          1
           Threads                                   1
           discuss.python.org,zulip                  1
           ghost.io, Mastodon, Lemmy, kbin           1
           huggingface, ollama                       1
           w3schools                                 1
           zulip                                     1
Austria    Mastodon                                  3
           Codeberg                                  1
           Codeberg, sourcehut                       1
           Fediverse / Mastodon                      1
           Fediverse/Mastodon                        1
           Mastodon, Fediverse                       1
           Mastodon, Xing                            1
           Mastodon/Fediverse                        1
           Matrix                                    1
           Sourcehut, mailing list, Element          1
Name: count, dtype: int64

In [20]:
# same to got the result for scecific country
country_grp['CommPlatformHaveEntr'].value_counts().loc['India']

CommPlatformHaveEntr
2                                                        3
lobste.rs                                                3
Whatsapp                                                 2
chatgpt                                                  2
daily.dev                                                2
4chan                                                    1
5                                                        1
7                                                        1
8                                                        1
ChatGPT                                                  1
Computer                                                 1
Daily.Dev                                                1
Facebook, Instagram, Whatsapp, Zoom, GoogleMeet,Teams    1
Good                                                     1
Huggingface                                              1
Instagram, Wonderful.dev                                 1
Lemmy                                                    1
No                                                       1
Official Docs, Element, Matrix                           1
SAP Blogs                                                1
Stack Overflow                                           1
Stack Overflow, Dev.to                                   1
Tex User Groups                                          1
Used last year: Dev.to, Discord, Reddit                  1
Yes                                                      1
irc libera                                               1
mastodon                                                 1
matrix, gitter, telegram                                 1
no                                                       1
vedhaa                                                   1
youtube                                                  1
Name: count, dtype: int64

In [21]:
country_grp['CommPlatformHaveEntr'].value_counts(normalize=True).loc['India']

CommPlatformHaveEntr
2                                                        0.078947
lobste.rs                                                0.078947
Whatsapp                                                 0.052632
chatgpt                                                  0.052632
daily.dev                                                0.052632
4chan                                                    0.026316
5                                                        0.026316
7                                                        0.026316
8                                                        0.026316
ChatGPT                                                  0.026316
Computer                                                 0.026316
Daily.Dev                                                0.026316
Facebook, Instagram, Whatsapp, Zoom, GoogleMeet,Teams    0.026316
Good                                                     0.026316
Huggingface                                              0.026316
Instagram, Wonderful.dev                                 0.026316
Lemmy                                                    0.026316
No                                                       0.026316
Official Docs, Element, Matrix                           0.026316
SAP Blogs                                                0.026316
Stack Overflow                                           0.026316
Stack Overflow, Dev.to                                   0.026316
Tex User Groups                                          0.026316
Used last year: Dev.to, Discord, Reddit                  0.026316
Yes                                                      0.026316
irc libera                                               0.026316
mastodon                                                 0.026316
matrix, gitter, telegram                                 0.026316
no                                                       0.026316
vedhaa                                                   0.026316
youtube                                                  0.026316
Name: proportion, dtype: float64

In [22]:
# same if we want to see the median salary for each country
country_grp['ConvertedCompYearly'].median()

Country
Afghanistan                               6121.0
Albania                                  26269.0
Algeria                                   6472.0
Andorra                                 200125.5
Angola                                    9578.0
                                          ...
Venezuela, Bolivarian Republic of...      9000.0
Viet Nam                                  7642.0
Yemen                                     5545.5
Zambia                                    1966.5
Zimbabwe                                 17500.0
Name: ConvertedCompYearly, Length: 177, dtype: float64

In [23]:
# to see for specific country, we easily use loc
country_grp['ConvertedCompYearly'].median().loc['Germany']

np.float64(81210.0)

In [24]:
country_grp['ConvertedCompYearly'].agg(['median', 'mean'])

                                        median           mean
Country
Afghanistan                             6121.0   12227.250000
Albania                                26269.0   47973.583333
Algeria                                 6472.0   15935.400000
Andorra                               200125.5  208763.750000
Angola                                  9578.0  149857.250000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    9000.0   17008.400000
Viet Nam                                7642.0  189894.192982
Yemen                                   5545.5   17582.500000
Zambia                                  1966.5    6594.875000
Zimbabwe                               17500.0   25662.500000

[177 rows x 2 columns]

In [25]:
country_grp['ConvertedCompYearly'].agg(['median', 'mean']).loc['Canada']

median     87550.000000
mean      100143.382514
Name: Canada, dtype: float64

In [26]:
country_grp['LanguageHaveWorkedWith'].str.contains('Python').sum() # we can't treat with SeriesGroupBy as series

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [27]:
# here applay method will help
country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              4
Albania                                 10
Algeria                                 23
Andorra                                  2
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    23
Viet Nam                                78
Yemen                                    6
Zambia                                   7
Zimbabwe                                 7
Name: LanguageHaveWorkedWith, Length: 177, dtype: int64