# Reading/Writing Data to Different Sources - Excel, JSON, SQL, Etc

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col='qname')

C:\Users\Maryam\AppData\Local\Temp\ipykernel_18256\3211394593.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/survey_results_public.csv', index_col='ResponseId')

In [3]:
pd.set_option('display.max_columns', 171)
pd.set_option('display.max_rows', 171)
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [4]:
filt = (df['Country'] == 'India')
india_df = df.loc[filt]
india_df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0

In [5]:
india_df.to_csv('data/modified.csv')

In [6]:
india_df.to_csv('data/modified.tsv', sep='\t')

In [8]:
india_df.to_excel('data/modified.xlsx')

In [9]:
test = pd.read_excel('data/modified.xlsx', index_col='ResponseId')
test.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",NaN,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,NaN,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,NaN,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,NaN,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once every 2 - 3 months,Less than one year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,NaN,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,NaN,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,NaN,NaN,NaN,NaN,NaN,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,NaN,NaN,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,NaN,NaN,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,NaN,NaN,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,NaN,NaN,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,NaN,Fireproof;LanceDB;Letta;Neo4j;Qdrant,NaN,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,NaN,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,NaN,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,NaN,NaN,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0
91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",NaN,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,NaN,NaN,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,NaN,NaN,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,NaN,NaN,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,NaN,NaN,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, definitely",Less than half of the time,NaN,Very favorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software engineering;Cybersecurity,Language processing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0
134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,NaN,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,NaN,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,NaN,NaN,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,NaN,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,NaN,AI agents have improved the quality of my code...,NaN,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,AutoGen (Microsoft),NaN,NaN,NaN,ChatGPT;Google Gemini;Microsoft Copilot,NaN,When I have ethical or security concerns about...,Problem solving,20109.0,9.0

In [13]:
india_df.to_json('data/modified.json')

In [12]:
india_df.to_json('data/modified.json', orient='records', lines=True)

In [14]:
test = pd.read_json('data/modified.json')
test.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
14,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",None,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,None,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,None,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,None,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,None,None,None,None,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,Less than once every 2 - 3 months,Less than one year,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,6.0
16,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",None,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,None,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,None,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,None,None,None,None,None,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,None,None,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,None,None,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,None,None,None,None,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,None,None,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",None,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,None,None,None,AI agents have increased my productivity.;AI a...,None,None,None,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,None,Fireproof;LanceDB;Letta;Neo4j;Qdrant,None,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,None,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,None,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,None,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
47,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,None,None,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,10.0
91,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",None,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,None,None,Yes,None,None,None,None,None,None,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,None,None,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,None,None,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,None,None,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,None,None,None,None,None,None,None,None,None,None,None,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,None,None,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",Less than half of the time,None,Very favorable,None,None,None,None,None,None,None,None,None,None,None,Software engineering;Cybersecurity,Language processing,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1.0,7.0
134,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,None,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,None,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,None,None,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,None,None,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,None,None,None,None,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,None,None,None,None,None,None,None,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,None,None,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,None,None,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),None,None,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,None,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,None,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,None,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,None,None,AI agents have improved the quality of my code...,None,None,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,None,None,None,AutoGen (Microsoft),None,None,None,ChatGPT;Google Gemini;Microsoft Copilot,None,When I have ethical or security concerns about...,Problem solving,20109.0,9.0

In [27]:
# read and write SQL
import sqlite3
import pandas as pd

In [30]:
conn = sqlite3.connect("data/analysis.db")

In [31]:
india_df.to_sql(
    "sample_table",
    conn,
    if_exists="replace",
    index=False
)

2547

In [32]:
df = pd.read_sql(
    "SELECT * FROM sample_table LIMIT 10",
    conn
)
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",None,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,None,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,None,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,None,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,None,None,None,None,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,Less than once every 2 - 3 months,Less than one year,None,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,6.0
1,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",None,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,None,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,None,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,None,None,None,None,None,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,None,None,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,None,None,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,None,None,None,None,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,None,None,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",None,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,None,None,None,AI agents have increased my productivity.;AI a...,None,None,None,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,None,Fireproof;LanceDB;Letta;Neo4j;Qdrant,None,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,None,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,None,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,None,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
2,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,None,None,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,10.0
3,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",None,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,None,None,Yes,None,None,None,None,None,None,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,None,None,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,None,None,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,None,None,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,None,None,None,None,None,None,None,None,None,None,None,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,None,None,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",Less than half of the time,None,Very favorable,None,None,None,None,None,None,None,None,None,None,None,Software engineering;Cybersecurity,Language processing,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1.0,7.0
4,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,None,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,None,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,None,None,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,None,None,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,None,None,None,None,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,None,None,None,None,None,None,None,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,None,None,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,None,None,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),None,None,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,None,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,None,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,None,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,None,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,None,None,AI agents have improved the quality of my code...,None,None,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,None,None,None,AutoGen (Microsoft),None,None,None,ChatGPT;Google Gemini;Microsoft Copilot,None,When I have ethical or security concerns about...,Problem solving,20109.0,9.0
5,I am a developer by profession,18-24 years old,Other (please specify):,"Independent contractor, freelancer, or self-em...",Volunteering (regularly),2.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,2.0,AI/ML engineer,None,None,None,"Yes, I influenced the purchase of a tool that ...",Work,11.0,5.0,10.0,9.0,6.0,7.0,8.0,12.0,4.0,14.0,None,7.0,8.0,6.0,9.0,12.0,14.0,2.0,4.0,5.0,15.0,None,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,I'm not sure,I have strongly considered changing my career ...,4.0,4.0,India,INR Indian rupee,NaN,Yes,C;C#;C++;HTML/CSS;Java;JavaScript,C;C++;HTML/CSS;JavaScript,C;C++;HTML/CSS;JavaScript,Java-Script,Java-Script,Yes,Microsoft SQL Server;MongoDB;MySQL,Microsoft SQL Server;MongoDB,Microsoft SQL Server;MongoDB,None,None,Yes,Docker;Firebase;Google Cloud;Netlify;npm;Verce...,Docker;Firebase;Google Cloud;Vercel;Vite;Webpack,Docker;Firebase;Google Cloud;Vercel;Vite;Webpack,None,None,Yes,ASP.NET;Express;Node.js;React;WordPress,ASP.NET;Express;NestJS;Next.js;Node.js;React,ASP.NET;Express;Node.js;React,None,None,Yes,Bolt;Jupyter Notebook/JupyterLab;PyCharm;Visua...,Visual Studio,Visual Studio,None,None,Tailwind CSS 4;hostinger;Large Language Model;...,Tailwind CSS 4;Google Gemini,Tailwind CSS 4;Google Gemini,None,None,Windows;ChromeOS,None,GitHub;Google Colab;Google Workspace;Trello,GitHub;Google Colab;Google Workspace,GitHub;Google Colab;Google Workspace,None,None,Stack Overflow;Discord;Dev.to;GitHub (public p...,Stack Overflow;YouTube;LinkedIn,Stack Overflow;YouTube;LinkedIn,None,None,Yes,Gemini (Flash general purpose models);Gemini (...,None,None,None,None,Yes,A few times per month or weekly,Less than one year,Less than once every 2 - 3 months,Chat (people);Long-form articles;Videos;Coding...,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, somewhat",Less than half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,"Good, but not great at handling complex tasks",Learning about a codebase;Debugging or fixing ...,None,None,Documenting code;Testing code,Project planning;Writing code,"AI solutions that are almost right, but not quite",None,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering;Business process automati...,Language processing;Vector databases for AI ap...,AI agents have increased my productivity.;AI a...,None,None,None,None,None,None,None,I am concerned about the accuracy of the infor...,None,None,None,None,None,None,None,ChatGPT;Google Gemini;Auto-GPT;Bolt.new;Blackb...,None,None,None,NaN,10.0
6,"I am not primarily a developer, but I write co...",18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Attending school (part-time),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,2.0,Data scientist,None,None,None,None,School,2.0,3.0,4.0,1.0,13.0,5.0,6.0,9.0,8.0,14.0,None,9.0,12.0,3.0,1.0,2.0,4.0,10.0,8.0,7.0,15.0,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,No,I have neither consider or transitioned into a...,2.0,2.0,India,INR Indian rupee,0.0,Yes,Python,C++,None,None,None,No,None,None,None,None,None,Yes,Pip,Cloudflare;Docker;Kubernetes;Microsoft Azure,None,None,None,Yes,None,None,None,None,None,Yes,Jupyter Notebook/JupyterLab,None,None,None,None,Large Language Model,Polars;Large Language Model;RAG;Google Gemini;...,Large Language Model,None,None,Windows,Ubuntu,GitHub;Obsidian,None,None,None,None,"GitHub (public projects, not private repos);Me...",Stack Overflow;Stack Exchange;Reddit;GitHub (p...,"GitHub (public projects, not private repos);Me...",None,None,Yes,Meta Llama (all models);Microsoft Phi-4 models...,None,None,None,None,Yes,A few times per month or weekly,Less than one year,I have never participated in Q&A on Stack Over...,None,8.0,None,6.0,4.0,2.0,9.0,3.0,5.0,13.0,15.0,None,"Yes, somewhat",More than half the time,"Yes, I use AI tools weekly",Indifferent,Somewhat trust,Bad at handling complex tasks,Search for answers,Learning about a codebase;Writing code;Documen...,Project planning;Debugging or fixing code;Test...,None,None,Debugging AI-generated code is more time-consu...,No,"No, but I plan to",Not at all or minimally,None,None,None,None,None,None,None,I am concerned about the accuracy of the infor...,None,None,The cost of using certain AI agent platforms i...,None,None,None,None,None,None,None,None,None,When I don’t trust AI’s answers;When I want to...,"Unique Thinking, Communication,",NaN,NaN

In [35]:
sql_df = pd.read_sql_query(
    "SELECT * FROM sample_table",
    conn,
    index_col="MainBranch"
)
sql_df

,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
MainBranch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",6.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Other onli...,6.0,"Developer, full-stack","1,000 to 4,999 employees",People manager,In-person,"Yes, I influenced the purchase of a substantia...",None,9.0,2.0,8.0,13.0,11.0,6.0,3.0,10.0,5.0,14.0,None,3.0,8.0,5.0,13.0,14.0,10.0,2.0,7.0,6.0,15.0,None,Fintech,8.0,10.0,12.0,9.0,3.0,7.0,1.0,2.0,5.0,4.0,6.0,11.0,13.0,15.0,14.0,None,No,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,None,None,None,None,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Yes,Less than once every 2 - 3 months,Less than one year,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,6.0
I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Student,Engaged in paid work (20-29 hours per week);En...,5.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",None,3.0,"Developer, mobile",20 to 99 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,9.0,3.0,6.0,7.0,2.0,8.0,1.0,4.0,5.0,14.0,None,7.0,4.0,8.0,14.0,5.0,12.0,3.0,13.0,9.0,15.0,None,Software Development,1.0,2.0,5.0,4.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,Yes,I have somewhat considered changing my career ...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...,Ada;Bash/Shell (all shells);C;C#;C++;Rust;Scal...,Ada;C;C#;C++;Rust;Scala;SQL,5,1,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;I...,Dynamodb;InfluxDB,InfluxDB,5,4,Yes,Amazon Web Services (AWS);APT;Bun;Chocolatey;D...,Ansible;Cargo;Cloudflare;Composer;Firebase;Goo...,Pip,5,4,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Astro;B...,Drupal;Fastify;NestJS;Next.js;Node.js;Nuxt.js;...,Drupal;React,4,4,No,None,None,None,None,None,c++23;Amazon Bedrock;Microsoft Fabric;Google G...,None,None,5,4,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Windows;MacOS;Ubuntu;Android;iOS;Debian;Linux ...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Notion;Obsidian,Notion;Obsidian,4,5,Stack Overflow;Stack Exchange;Discord;Reddit;D...,None,None,5,5,Yes,Alibaba Cloud Qwen models;Amazon Titan models;...,None,None,None,None,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,Message Boards;Videos;Coding challenges;Logic ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks",Search for answers,None,None,Documenting code,Learning about a codebase;Project planning;Wri...,"AI solutions that are almost right, but not qu...",None,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Language processing;Agent/multi-agent orchestr...,None,None,None,AI agents have increased my productivity.;AI a...,None,None,None,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,None,Fireproof;LanceDB;Letta;Neo4j;Qdrant,None,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,None,Galileo;Honeycomb;Metero;New Relic;opik;Snyk,None,ChatGPT;AgentGPT;Auto-GPT;Devin AI;Glean (Ente...,None,When I don’t trust AI’s answers;When I have et...,5,NaN,7.0
I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,None,I'm not sure,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,Yes,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;Groovy;HTML/CSS;Jav...,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,None,None,Yes,Cassandra;Elasticsearch,Cassandra;Elasticsearch,Cassandra;Elasticsearch,None,None,Yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,10.0
I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,6.0,"Developer, full-stack",20 to 99 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I endorsed a tool that was open-source an...",Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Yes,I have strongly considered changing my career ...,NaN,NaN,India,INR Indian rupee,50.0,Yes,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,HTML/CSS;JavaScript;PHP;Python;SQL;TypeScript;VBA,"Javascript,php,node,react,jQuery,MySQL,",None,Yes,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,None,None,Yes,None,None,None,None,None,None,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,Django;Express;FastAPI;Fastify;Flask;jQuery;Ne...,None,None,Yes,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,Cursor;Notepad++;PhpStorm;PyCharm;Rider;Sublim...,None,None,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,Tailwind CSS 4;hostinger;Odoo,None,None,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,Ubuntu;Windows Subsystem for Linux (WSL);Debia...,None,None,None,None,None,None,None,None,None,None,None,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,Anthropic: Claude Sonnet;DeepSeek (R- Reasonin...,None,None,Yes,Less than once every 2 - 3 months,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Long-form articles;Videos;Coding challenges;Di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"Yes, definitely",Less than half of the time,None,Very favorable,None,None,None,None,None,None,None,None,None,None,None,Software engineering;Cybersecurity,Language processing,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1.0,7.0
I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,10.0,"Developer, full-stack","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,10.0,1.0,3.0,5.0,9.0,13.0,6.0,2.0,4.0,14.0,None,9.0,3.0,11.0,6.0,7.0,2.0,4.0,12.0,1.0,15.0,None,"Transportation, or Supply Chain",2.0,3.0,6.0,7.0,10.0,11.0,1.0,9.0,12.0,14.0,8.0,13.0,4.0,15.0,5.0,All are there in my case are and are at equal ...,Yes,I have transitioned into a new career and/or i...,5.0,2.0,India,INR Indian rupee,1730000.0,Yes,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;PowerShell;TypeScript,HTML/CSS;JavaScript;TypeScript,None,None,Yes,Microsoft SQL Server;MySQL;PostgreSQL,Microsoft SQL Server;MongoDB;MySQL;PostgreSQL,Microsoft SQL Server;MySQL;PostgreSQL,None,None,Yes,npm,npm,npm,Azure,Azure,Yes,jQuery,None,None,None,None,Yes,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,None,None,None,None,None,None,None,Windows;MacOS,Windows,GitHub;Markdown File;Notion,GitHub;Markdown File,GitHub;Markdown File,None,None,Stack Overflow;Discord;Reddit;Dev.to;GitHub (p...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,Stack Overflow;Reddit;Dev.to;YouTube;LinkedIn;...,None,None,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),None,None,Yes,Multiple times per day,Between 5 and 10 years,A few times per week,Chat (people);Message Boards;Long-form article...,13.0,NaN,3.0,11.0,2.0,1.0,8.0,4.0,14.0,15.0,None,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,Search for answers;Learning new concepts or te...,Writing code;Debugging or fixing code;Testing ...,Learning about a codebase;Project planning;Doc...,Creating or maintaining documentation,None,Debugging AI-generated code is more time-consu...,Nope,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,None,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,None,None,AI agents have improved the quality of my code...,None,None,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,None,None,None,AutoGen (Microsoft),None,None,None,ChatGPT;Google Gemini;Microsoft Copilot,None,When I have ethical or security concerns about...,Problem solving,20109.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
I code primarily as a hobby,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Not employed,None,NaN,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Videos (not associated ...,"No, I learned something that was not related t...",None,3.0,Student,None,None,None,None,Personal Project,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,Yes,I have neither consider or transitioned into a...,NaN,2.0,India,INR Indian rupee,NaN,Yes,HTML/CSS;Java;JavaScript;Python;Rust;TypeScript,Rust;TypeScript,Rust;TypeScript,None,None,Yes,MySQL;Redis;SQLite,None,None,None,None,Yes,Amazon Web Services (AWS);Ansible;Homebrew;Kub...,Kubernetes;npm,Kubernetes;npm,None,None,Yes,Node.js;React;Axum,Next.js;React;Axum,React;Axum,None,None,None,Cursor;Visual Studio Code,Cursor,Cursor,None,None,Tailwind CSS 4,Tailwind CSS 4,Tailwind CSS 4,None,None,MacOS,MacOS,None,None,None,None,None,Stack Overflow;YouTube,None,None,None,None,No,None,None,None,None,None,Yes,Less than once per month or monthly,Less than one year,Less than once every 2 - 3 months,Chat (people),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,"No, not really",None,"Yes, I use AI tools daily",Favorable,Somewhat trust,Very well at handling complex tasks,None,Project planning;Generating content or synthet...,Learning about a codebase;Writing code;Documen...,Debugging or fixing code;Testing code;Committi...,Search for answers,I’ve become less confident in my own problem-s...,None,"No, but I plan to","Yes, to a great extent",None,None,None,None,None,None,None,Integrating AI agents with my existing tools a...,None,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,None,None,None,None,None,None,None,None,None,When I’m stuck and can’t explain the problem,Maths,NaN,NaN
I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,1.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,5.0,Data engineer,20 to 99 employees,None,In-person,"Yes, I influenced the purchase of a substantia...",Work,4.0,6.0,1.0,3.0,5.0,2.0,8.0,9.0,7.0,10.0,None,7.0,6.0,2.0,1.0,8.0,9.0,5.0,3.0,4.0,10.0,None,Software Development,13.0,10.0,6.0,1.0,4.0,9.0,5.0,14.0,2.0,12.0,7.0,8.0,3.0,15.0,11.0,None,Yes,I have strongly considered changing my career ...,10.0,4.0,India,INR Indian rupee,750000.0,Yes,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,Java;JavaScript;Python,Java;JavaScript;Python,PySpark,None,Yes,Databricks SQL;Dynamodb;MySQL;Snowflake;Amazon...,None,None,None,None,Yes,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,Amazon Web Services (AWS);Docker;Kubernetes;Te...,None,None,Yes,Express;Node.js,Express;Node.js;Spring Boot,Express;Node.js,None,None,Yes,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,Claude Code;Jupyter Notebook/JupyterLab;Visual...,None,None,None,None,None,None,None,Windows;Ubuntu,Windows;Ubuntu,GitHub;GitLab,GitHub;GitLab,GitHub;GitLab,None,None,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,Stack Overflow;YouTube;LinkedIn;Medium,None,None,Yes,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,None,None,Yes,Daily or almost daily,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Job board,3.0,5.0,9.0,6.0,4.0,7.0,2.0,8.0,1.0,10.0,None,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,None,None,None,Learning about a codebase;Project planning;Wri...,None,"AI solutions that are almost right, but not quite",None,None,"Yes, somewhat",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,8.0
I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",None,10.0,"Developer, front-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,4.0,5.0,6.0,3.0,8.0,1.0,9.0,2.0,7.0,10.0,None,7.0,9.0,4.0,2.0,6.0,5.0,1.0,3.0,8.0,10.0,None,Software Development,6.0,12.0,4.0,9.0,7.0,11.0,3.0,14.0,13.0,5.0,2.0,1.0,8.0,15.0,10.0,None,Yes,I have transitioned into a new career and/or i...,NaN,NaN,India,INR Indian rupee,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,"Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,Neither good or bad at handling complex tasks,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,5.0

In [36]:
posts_df = pd.read_json('https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/master/Python/Flask_Blog/snippets/posts.json')
posts_df.head()

,title,content,user_id
0,My Updated Post,My first updated post!\r\n\r\nThis is exciting!,1
1,A Second Post,This is a post from a different user...,2
2,Top 5 Programming Lanaguages,"Te melius apeirian postulant cum, labitur admo...",1
3,Sublime Text Tips and Tricks,"Ea vix dico modus voluptatibus, mel iudico sua...",1
4,Best Python IDEs,"Elit contentiones nam no, sea ut consul adipis...",1