In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
    'first': ['Maryam', 'Tia', 'Tima', 'Sara', np.nan, None, 'NA'], 
    'last': ['Skaik', 'lulu', 'lulu', 'ahmed', np.nan, np.nan, 'Missing'], 
    'email': ['MaryamSkaik@gmail.com', 'Tialulu@email.com', 'Timalulu@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['22', '20', '20', '25', None, None, 'Missing']
}

In [3]:
df = pd.DataFrame(people)
df

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
3    Sara    ahmed                   None       25
4     NaN      NaN                    NaN     None
5    None      NaN    Anonymous@email.com     None
6      NA  Missing                     NA  Missing

In [4]:
df.dropna() # drop all None

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
6      NA  Missing                     NA  Missing

In [6]:
df.dropna(axis='index', how='any') # give same result
# index mean drop rows contains missing values, but if we put columns, then it will drop the whole column contain a missing value
# and for how, this specify how to drop rows, we choose drop row if any of it's value is missing

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
6      NA  Missing                     NA  Missing

In [8]:
# if we try how=all
df.dropna(axis='index', how='all') # just drop rows with all None or NaN

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
3    Sara    ahmed                   None       25
5    None      NaN    Anonymous@email.com     None
6      NA  Missing                     NA  Missing

In [9]:
df.dropna(axis='columns', how='all') # same df, since no columns contains all missing values

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
3    Sara    ahmed                   None       25
4     NaN      NaN                    NaN     None
5    None      NaN    Anonymous@email.com     None
6      NA  Missing                     NA  Missing

In [10]:
df.dropna(axis='columns', how='any') # give empty df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [11]:
# we ca specify which columns to focus on for missing values, using subset paramerer
df.dropna(axis='index', how='any', subset=['email']) # cheack only one value, even with how=all

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
5    None      NaN    Anonymous@email.com     None
6      NA  Missing                     NA  Missing

In [12]:
df.dropna(axis='index', how='all', subset=['email']) # same result

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
5    None      NaN    Anonymous@email.com     None
6      NA  Missing                     NA  Missing

In [13]:
# to specify more than one columns to check
df.dropna(axis='index', how='all', subset=['last', 'email']) # mean must email and last be missing to drop

    first     last                  email      age
0  Maryam    Skaik  MaryamSkaik@gmail.com       22
1     Tia     lulu      Tialulu@email.com       20
2    Tima     lulu     Timalulu@email.com       20
3    Sara    ahmed                   None       25
5    None      NaN    Anonymous@email.com     None
6      NA  Missing                     NA  Missing

In [14]:
# ok, now want to solve these values with string = NA, or missing, so we can drop easily
df.replace('NA', np.nan, inplace=True)
df.replace('Missing', np.nan, inplace=True)
df

    first   last                  email   age
0  Maryam  Skaik  MaryamSkaik@gmail.com    22
1     Tia   lulu      Tialulu@email.com    20
2    Tima   lulu     Timalulu@email.com    20
3    Sara  ahmed                   None    25
4     NaN    NaN                    NaN  None
5    None    NaN    Anonymous@email.com  None
6     NaN    NaN                    NaN   NaN

In [15]:
# now we can run df.dropna
df.dropna()

    first   last                  email age
0  Maryam  Skaik  MaryamSkaik@gmail.com  22
1     Tia   lulu      Tialulu@email.com  20
2    Tima   lulu     Timalulu@email.com  20

In [16]:
# to see missing values as T, F
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [17]:
# if we process missing values with different way, mean we don't want to drop the whole row contains a missing value
# we can fill it with value we want
df.fillna("MISSING")

     first     last                  email      age
0   Maryam    Skaik  MaryamSkaik@gmail.com       22
1      Tia     lulu      Tialulu@email.com       20
2     Tima     lulu     Timalulu@email.com       20
3     Sara    ahmed                MISSING       25
4  MISSING  MISSING                MISSING  MISSING
5  MISSING  MISSING    Anonymous@email.com  MISSING
6  MISSING  MISSING                MISSING  MISSING

In [18]:
# or we can fill with zeros, if we care about numbers, like age, score, gpa 😏
df.fillna(0)

    first   last                  email age
0  Maryam  Skaik  MaryamSkaik@gmail.com  22
1     Tia   lulu      Tialulu@email.com  20
2    Tima   lulu     Timalulu@email.com  20
3    Sara  ahmed                      0  25
4       0      0                      0   0
5       0      0    Anonymous@email.com   0
6       0      0                      0   0

In [19]:
# get mean of ages, but check dt before
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [21]:
# we find age is object, so take the mean directly will cause a problem
df['age'].mean()

TypeError: can only concatenate str (not "int") to str

In [25]:
# first change age data type
df['age'] = df['age'].astype(float)
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [26]:
# now we can safely get the mean
df['age'].mean()

np.float64(21.75)