In [1]:
people = {
    "first": ["Maryam", 'Tia', 'Tima'], 
    "last": ["Skaik", 'lulu', 'lulu'], 
    "email": ["MarymSkaik@gmail.com", 'Tialulu@email.com', 'Timalulu@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com

In [5]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [6]:
# we can change columns names by assign new values to columns
df.columns = ['first_name', 'last_name', 'email']
df

  first_name last_name                 email
0     Maryam     Skaik  MarymSkaik@gmail.com
1        Tia      lulu     Tialulu@email.com
2       Tima      lulu    Timalulu@email.com

In [7]:
df.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [8]:
# now if we want to change names from upper case to lower case and vice versa
# we can do this with list comprehension
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                 EMAIL
0     Maryam     Skaik  MarymSkaik@gmail.com
1        Tia      lulu     Tialulu@email.com
2       Tima      lulu    Timalulu@email.com

In [10]:
# if we want to replace _ with space
df.columns = df.columns.str.replace('_', ' ')
df

  FIRST NAME LAST NAME                 EMAIL
0     Maryam     Skaik  MarymSkaik@gmail.com
1        Tia      lulu     Tialulu@email.com
2       Tima      lulu    Timalulu@email.com

In [12]:
# because we need names with _, we will make replace again, and also convert it to lower case
df.columns = df.columns.str.replace(' ', '_')
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name                 email
0     Maryam     Skaik  MarymSkaik@gmail.com
1        Tia      lulu     Tialulu@email.com
2       Tima      lulu    Timalulu@email.com

In [15]:
# another way to rename columns, is treat with it as dictionary, key is old name, and value is the new
df.rename(columns={'first_name': 'first', 'last_name': 'last'})

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com

In [16]:
# but dataframe still has the old names, so we have to add an inplace parameter
df

  first_name last_name                 email
0     Maryam     Skaik  MarymSkaik@gmail.com
1        Tia      lulu     Tialulu@email.com
2       Tima      lulu    Timalulu@email.com

In [17]:
# fix
df.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True)
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com

In [19]:
# now we updates columns names, but what if we want to update the data in the rows ?
# fisrt way as assignment with loc, mean get the index of row, and columns name then change the cell value
df.loc[2, 'last'] = 'el-lulu'
df

    first     last                 email
0  Maryam    Skaik  MarymSkaik@gmail.com
1     Tia     lulu     Tialulu@email.com
2    Tima  el-lulu    Timalulu@email.com

In [20]:
# same we can change the whole row data
df.loc[2] = ['saly', 'ahmed', 'salyahmed@email.com']
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    saly  ahmed   salyahmed@email.com

In [23]:
# we can do same with at instead of loc
df.loc[2, ['first','last']] = ['Tima', 'lulu']
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu   salyahmed@email.com

In [24]:
filt = (df['email'] == 'salyahmed@email.com')
df.loc[filt, 'email'] = 'Timalulu@email.com'
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com

In [26]:
# we updated single row of data, now we want to update multiple rows of data
df['email'] = df['email'].str.lower()
df['email']

0    marymskaik@gmail.com
1       tialulu@email.com
2      timalulu@email.com
Name: email, dtype: object

In [27]:
df

    first   last                 email
0  Maryam  Skaik  marymskaik@gmail.com
1     Tia   lulu     tialulu@email.com
2    Tima   lulu    timalulu@email.com

In [28]:
# using applay function
df['email'].apply(len)

0    20
1    17
2    18
Name: email, dtype: int64

In [29]:
# we can benifit from it, if we have a function, and want to applay to data
def update_email(email):
    return email.upper()

In [30]:
df.email.apply(update_email)

0    MARYMSKAIK@GMAIL.COM
1       TIALULU@EMAIL.COM
2      TIMALULU@EMAIL.COM
Name: email, dtype: object

In [31]:
df.email = df.email.apply(update_email)
df

    first   last                 email
0  Maryam  Skaik  MARYMSKAIK@GMAIL.COM
1     Tia   lulu     TIALULU@EMAIL.COM
2    Tima   lulu    TIMALULU@EMAIL.COM

In [32]:
# now return it to lower case using applay and lambda
df.email = df.email.apply(lambda x : x.lower())
df

    first   last                 email
0  Maryam  Skaik  marymskaik@gmail.com
1     Tia   lulu     tialulu@email.com
2    Tima   lulu    timalulu@email.com

In [34]:
df.apply(len) # return # of values to each columns

first    3
last     3
email    3
dtype: int64

In [35]:
# same as:
df.apply(len, axis='columns')

0    3
1    3
2    3
dtype: int64

In [37]:
# to get max from each column
df.apply(pd.Series.max)

first                  Tima
last                   lulu
email    timalulu@email.com
dtype: object

In [38]:
df.apply(lambda x: x.min())

first                  Maryam
last                    Skaik
email    marymskaik@gmail.com
dtype: object

In [41]:
# now use applaymap
df.applymap(len)

C:\Users\Maryam\AppData\Local\Temp\ipykernel_2500\2382766492.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first  last  email
0      6     5     20
1      3     4     17
2      4     4     18

In [43]:
df.map(len) # to avoid warning

   first  last  email
0      6     5     20
1      3     4     17
2      4     4     18

In [45]:
df.map(str.lower)

    first   last                 email
0  maryam  skaik  marymskaik@gmail.com
1     tia   lulu     tialulu@email.com
2    tima   lulu    timalulu@email.com

In [47]:
# replace
df['first'] = df['first'].replace({'Maryam': 'Mariam', 'Tima': 'Saly'})
df

    first   last                 email
0  Mariam  Skaik  marymskaik@gmail.com
1     Tia   lulu     tialulu@email.com
2    Saly   lulu    timalulu@email.com