# Fix Messy Exam Data Step-by-Step for Analysis

In [1]:
import pandas as pd

In [2]:
pd.read_csv('./Expanded_data_with_more_features.csv')

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,5 - 10,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,5 - 10,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,5 - 10,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,5 - 10,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,5 - 10,64,60,58

In [3]:
data = pd.read_csv('./Expanded_data_with_more_features.csv')
data.tail(10)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
30631,765,male,group E,some high school,standard,none,married,sometimes,no,3.0,school_bus,< 5,80,65,66
30632,778,female,group D,some college,standard,none,married,regularly,no,3.0,private,5 - 10,82,88,97
30633,783,female,group C,master's degree,standard,completed,married,never,no,2.0,school_bus,5 - 10,84,99,99
30634,785,male,group A,associate's degree,free/reduced,completed,NaN,sometimes,no,2.0,school_bus,5 - 10,65,60,60
30635,794,male,group C,some college,standard,none,married,regularly,no,2.0,school_bus,5 - 10,58,53,49
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,5 - 10,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,5 - 10,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,5 - 10,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,5 - 10,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,5 - 10,64,60,58

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           30641 non-null  int64
 1   Gender               30641 non-null  object
 2   EthnicGroup          28801 non-null  object
 3   ParentEduc           28796 non-null  object
 4   LunchType            30641 non-null  object
 5   TestPrep             28811 non-null  object
 6   ParentMaritalStatus  29451 non-null  object
 7   PracticeSport        30010 non-null  object
 8   IsFirstChild         29737 non-null  object
 9   NrSiblings           29069 non-null  float64
 10  TransportMeans       27507 non-null  object
 11  WklyStudyHours       29686 non-null  object
 12  MathScore            30641 non-null  int64
 13  ReadingScore         30641 non-null  int64
 14  WritingScore         30641 non-null  int64
dtypes: float64(1), int64(4), object(10)
memory usage: 3.5+ MB

In [5]:
data.columns

Index(['Unnamed: 0', 'Gender', 'EthnicGroup', 'ParentEduc', 'LunchType',
       'TestPrep', 'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild',
       'NrSiblings', 'TransportMeans', 'WklyStudyHours', 'MathScore',
       'ReadingScore', 'WritingScore'],
      dtype='object')

In [9]:
data.drop(columns=['Unnamed: 0', 'TestPrep', 'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild'], inplace=True)

In [10]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,female,NaN,bachelor's degree,standard,3.0,school_bus,< 5,71,71,74
1,female,group C,some college,standard,0.0,NaN,5 - 10,69,90,88
2,female,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
3,male,group A,associate's degree,free/reduced,1.0,NaN,5 - 10,45,56,42
4,male,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...
30636,female,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,male,group E,high school,standard,1.0,private,5 - 10,58,53,51
30638,female,NaN,high school,free/reduced,1.0,private,5 - 10,61,70,67
30639,female,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93
30640,male,group B,some college,standard,1.0,school_bus,5 - 10,64,60,58

In [11]:
data.columns

Index(['Gender', 'EthnicGroup', 'ParentEduc', 'LunchType', 'NrSiblings',
       'TransportMeans', 'WklyStudyHours', 'MathScore', 'ReadingScore',
       'WritingScore'],
      dtype='object')

In [12]:
data.rename(columns= {'NrSiblings':'NumberofSiblings'}, inplace=True)

In [13]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,female,NaN,bachelor's degree,standard,3.0,school_bus,< 5,71,71,74
1,female,group C,some college,standard,0.0,NaN,5 - 10,69,90,88
2,female,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
3,male,group A,associate's degree,free/reduced,1.0,NaN,5 - 10,45,56,42
4,male,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...
30636,female,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,male,group E,high school,standard,1.0,private,5 - 10,58,53,51
30638,female,NaN,high school,free/reduced,1.0,private,5 - 10,61,70,67
30639,female,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93
30640,male,group B,some college,standard,1.0,school_bus,5 - 10,64,60,58

In [14]:
data.duplicated().sum()

np.int64(9)

In [16]:
data.drop_duplicates(inplace=True)

In [17]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,female,NaN,bachelor's degree,standard,3.0,school_bus,< 5,71,71,74
1,female,group C,some college,standard,0.0,NaN,5 - 10,69,90,88
2,female,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
3,male,group A,associate's degree,free/reduced,1.0,NaN,5 - 10,45,56,42
4,male,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
...,...,...,...,...,...,...,...,...,...,...
30635,male,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
30636,female,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,male,group E,high school,standard,1.0,private,5 - 10,58,53,51
30638,female,NaN,high school,free/reduced,1.0,private,5 - 10,61,70,67
30639,female,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [18]:
data.isna().sum()

Gender                 0
EthnicGroup         1840
ParentEduc          1845
LunchType              0
NumberofSiblings    1571
TransportMeans      3134
WklyStudyHours       955
MathScore              0
ReadingScore           0
WritingScore           0
dtype: int64

In [19]:
data.isna().sum().sum()

np.int64(9345)

In [20]:
data.dropna(inplace=True)

In [21]:
data.isna().sum().sum()

np.int64(0)

In [22]:
data.Gender.unique()

array(['female', 'male'], dtype=object)

In [24]:
data['Gender'] = data['Gender'].apply(lambda x: 1 if x == 'female' else 0)

In [25]:
data

,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
2,1,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
4,0,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
5,1,group B,associate's degree,standard,1.0,school_bus,5 - 10,73,84,79
6,1,group B,some college,standard,1.0,private,5 - 10,85,93,89
7,0,group B,some college,free/reduced,1.0,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...
30634,0,group A,associate's degree,free/reduced,2.0,school_bus,5 - 10,65,60,60
30635,0,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
30636,1,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
30637,0,group E,high school,standard,1.0,private,5 - 10,58,53,51
30639,1,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [26]:
data.reset_index(inplace=True)

In [27]:
data

,index,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,2,1,group B,master's degree,standard,4.0,school_bus,< 5,87,93,91
1,4,0,group C,some college,standard,0.0,school_bus,5 - 10,76,78,75
2,5,1,group B,associate's degree,standard,1.0,school_bus,5 - 10,73,84,79
3,6,1,group B,some college,standard,1.0,private,5 - 10,85,93,89
4,7,0,group B,some college,free/reduced,1.0,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...,...
22338,30634,0,group A,associate's degree,free/reduced,2.0,school_bus,5 - 10,65,60,60
22339,30635,0,group C,some college,standard,2.0,school_bus,5 - 10,58,53,49
22340,30636,1,group D,high school,standard,2.0,school_bus,5 - 10,59,61,65
22341,30637,0,group E,high school,standard,1.0,private,5 - 10,58,53,51
22342,30639,1,group D,associate's degree,standard,3.0,school_bus,5 - 10,82,90,93

In [28]:
data['NumberofSiblings'] = data['NumberofSiblings'].astype(int)

In [29]:
data

,index,Gender,EthnicGroup,ParentEduc,LunchType,NumberofSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,2,1,group B,master's degree,standard,4,school_bus,< 5,87,93,91
1,4,0,group C,some college,standard,0,school_bus,5 - 10,76,78,75
2,5,1,group B,associate's degree,standard,1,school_bus,5 - 10,73,84,79
3,6,1,group B,some college,standard,1,private,5 - 10,85,93,89
4,7,0,group B,some college,free/reduced,1,private,> 10,41,43,39
...,...,...,...,...,...,...,...,...,...,...,...
22338,30634,0,group A,associate's degree,free/reduced,2,school_bus,5 - 10,65,60,60
22339,30635,0,group C,some college,standard,2,school_bus,5 - 10,58,53,49
22340,30636,1,group D,high school,standard,2,school_bus,5 - 10,59,61,65
22341,30637,0,group E,high school,standard,1,private,5 - 10,58,53,51
22342,30639,1,group D,associate's degree,standard,3,school_bus,5 - 10,82,90,93

In [30]:
data.to_excel('clean_exam_data.xlsx')

In [32]:
data.to_csv('clean_csv_exam_data.csv')